### PR TITLE
Added Carthage support

### PR DESCRIPTION
**Pull request by alvivi**
Hi there. I added support for carthage (https://github.com/Carthage/Carthage) and proper framework support to the XCode project. I did not tested it against Cocoapods but should work properly. Even if not merged, this could be useful for someone.

### CODE REVIEW

**Comment by jkasten2** [comment]
Thanks for the pull request, I'll start reviewing your changes next week and get back to you.

**Comment by Danappelxx** [comment]
Any updates?

**Comment by jkasten2** [comment]
Sorry for the delay on this, we are working on a large update and will add Carthage after the release.

**Comment by Danappelxx** [comment]
I went ahead and forked the repository and added Carthage support. [Here it is](https://github.com/losaltoshacks/OneSignal-iOS-SDK) if anyone is interested.

Will the update require any changes to apps using it? Also, if I may ask, what's in the update? :stuck_out_tongue:

**Comment by jkasten2** [comment]
@Danappelxx Thanks for the fork, I'll use it as a reference when adding it to our main repo.

I am working bring this repo in sync with the additions and improvements I made to the 2.0 release of our [OneSignal Android SDK](https://github.com/one-signal/OneSignal-Android-SDK/releases). Including optimizing network calls, offline tags, geotagging, Xcode Unit tests, and a number of other smaller misc fixes.

**Comment by Danappelxx** [comment]
Great! :+1:

**Comment by entotsu** [comment]
GJ!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! :+1:  :+1:  :+1:

**Comment by entotsu** [comment]
+1

**Comment by drajak** [comment]
for Carthage support. Using dynamic framework. https://github.com/drajak/OneSignalKit

**Comment by kzzr2on** [comment]
Hi,

**Comment by TofPlay** [comment]
@drajak is it an official support of Carthage for OneSignal?

**Comment by drajak** [comment]
@TofPlay I have not written any code myself. everything is copied from their official static library(which is this project). I just converted the project into dynamic framework and added support for Carthage. Feel free to download the project and go through it.

**Comment by TofPlay** [comment]
@jkasten2 Any news about official Carthage support?

**Comment by ArtisOracle** [comment]
+1

**Comment by jkasten2** [comment]
I'll see about getting Carthage into the next minor within the next month.

**Comment by dirkoswanepoel** [comment]
@jkasten2 Any news about Carthage support?

**Comment by JKalash** [comment]
@dirkoswanepoel OneSignal supports Carthage as of [2.0](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/2.0)

**Pull request closed without merging**
