### PR TITLE
iOS 15 Feature Notification action icons

### PR DESCRIPTION
**Pull request by emawby**
This is branched off of main which currently has some broken IAM unit tests (already fixed in another PR).

iOS 15 introduced UNNotificationActionIcons ([read about them here](https://onesignal.com/blog/ios-notification-changes-updates-from-apples-wwdc-21/)). This PR supports adding action icons from OneSignal notification payloads.

There are 2 types of icons:
1. System icons which are [SF Symbols](https://developer.apple.com/sf-symbols/) included in all iOS Apps.
2. Template icons which are icon resources included by developers in their app bundles.

Icons can be added to notification actions through a new initializer method, and can themselves be initialized as either system or template icons.

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/991)

### CODE REVIEW

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/991)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @emawby, @Jeasmine, and @nan-li)

___
*[iOS_SDK/OneSignalSDK/Source/OneSignalHelper.m, line 577 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/991#-MjFwYKc9XCROsmMHmA4:-MjFwYKd0GnaW1JNt886:b-h1vm6o) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/80b8131d3448d935f331db0f81d08b971c614ec9/iOS_SDK/OneSignalSDK/Source/OneSignalHelper.m#L577)):*
> ```objc
>             icon = [UNNotificationActionIcon iconWithTemplateImageName:button[@"templateIcon"]];
>         }
>         return [UNNotificationAction actionWithIdentifier:button[@"id"]
> ```

The selector `actionWithIdentifier:title:options:icon:` is new in the beta version of Xcode:
https://developer.apple.com/documentation/usernotifications/unnotificationaction/3747237-actionwithidentifier?language=objc

We will need to use reflection to call this so it can compile with Xcode 11.0 as we do so to keep bit code compatibility for the release build.

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/991)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @emawby, @Jeasmine, and @nan-li)

___
*[iOS_SDK/OneSignalSDK/Source/OneSignalHelper.m, line 580 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/991#-MjG-VqlBhySeJN3piyO:-MjG-VqlBhySeJN3piyP:b-ebvn) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/80b8131d3448d935f331db0f81d08b971c614ec9/iOS_SDK/OneSignalSDK/Source/OneSignalHelper.m#L580)):*
> ```objc
>                                                     title:button[@"text"]
>                                                   options:UNNotificationActionOptionForeground
>                                                      icon:icon];
> ```

`icon` might be `nil` here, not sure if the iOS API is ok with that.

**Review by emawby — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/991)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @emawby, @Jeasmine, @jkasten2, and @nan-li)

___
*[iOS_SDK/OneSignalSDK/Source/OneSignalHelper.m, line 580 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/991#-MjG-VqlBhySeJN3piyO:-MjUwr2o4xd66yiZgK9E:b-v8bn6p) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/80b8131d3448d935f331db0f81d08b971c614ec9/iOS_SDK/OneSignalSDK/Source/OneSignalHelper.m#L580)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

`icon` might be `nil` here, not sure if the iOS API is ok with that.
</blockquote></details>

the icon parameter is marked nullable so this should be fine

**Review by emawby — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/991)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @Jeasmine, @jkasten2, and @nan-li)

___
*[iOS_SDK/OneSignalSDK/Source/OneSignalHelper.m, line 577 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/991#-MjFwYKc9XCROsmMHmA4:-MjVG0M4C9x-cP-vu0op:bkljqbb) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/80b8131d3448d935f331db0f81d08b971c614ec9/iOS_SDK/OneSignalSDK/Source/OneSignalHelper.m#L577)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

The selector `actionWithIdentifier:title:options:icon:` is new in the beta version of Xcode:
https://developer.apple.com/documentation/usernotifications/unnotificationaction/3747237-actionwithidentifier?language=objc

We will need to use reflection to call this so it can compile with Xcode 11.0 as we do so to keep bit code compatibility for the release build.
</blockquote></details>

Done but its a bit ugly since we cannot use performSelector

**Review by jkasten2 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/991)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Jeasmine and @nan-li)

___
*[iOS_SDK/OneSignalSDK/Source/OneSignalHelper.m, line 577 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/991#-MjFwYKc9XCROsmMHmA4:-MjVUIBM9GpxW1yDcgPl:bwgkxsi) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/80b8131d3448d935f331db0f81d08b971c614ec9/iOS_SDK/OneSignalSDK/Source/OneSignalHelper.m#L577)):*
<details><summary><i>Previously, emawby (Elliot Mawby) wrote…</i></summary><blockquote>

Done but its a bit ugly since we cannot use performSelector
</blockquote></details>

no problem, if you think of a better way in the future we can clean it up.

**Pull request merged**
