### PR TITLE
Fix: share extension crash

### LINKED ISSUE #1073: Share Extension assertion failure in +[OneSignalUNUserNotificationCenter registerDelegate], OneSignal.m:111
**Description:**
ShareExtension crashes due to the following exception.

```swift
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'bundleProxyForCurrentProcess is nil: mainBundle.bundleURL file:///Users/jun.morita/Library/Developer/CoreSimulator/Devices/DC881930-0C40-4E8D-820B-F961EA1BCA28/data/Containers/Bundle/Application/BD84418E-C877-47F7-8B06-2BCA190F25DA/vLive-viewer-ios.app/PlugIns/RealityShareExtension.appex/'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000110a7ad44 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00000001096bba65 objc_exception_throw + 48
	2   Foundation                          0x000000010c513634 _userInfoForFileAndLine + 0
	3   UserNotifications                   0x000000010ff3e841 __53+[UNUserNotificationCenter currentNotificationCenter]_block_invoke + 1027
	4   libdispatch.dylib                   0x000000010bbd9b25 _dispatch_client_callout + 8
	5   libdispatch.dylib                   0x000000010bbdacdd _dispatch_once_callout + 20
	6   UserNotifications                   0x000000010ff3e43c +[UNUserNotificationCenter currentNotificationCenter] + 101
	7   Umbrella                            0x0000000134faef74 +[OneSignalUNUserNotificationCenter registerDelegate] + 36
	8   Umbrella                            0x0000000134faedf8 +[OneSignalUNUserNotificationCenter setup] + 56
	9   Umbrella                            0x0000000134f856af +[UIApplication(OneSignal) setupUNUserNotificationCenterDelegate] + 63
	10  Umbrella                            0x0000000134f85594 +[UIApplication(OneSignal) load] + 628
	11  libobjc.A.dylib                     0x00000001096a936c load_images + 806
	12  dyld                                0x000000010940ade8 _ZN5dyld412RuntimeState14notifyObjCInitEPKNS_6LoaderE + 170
	13  dyld                                0x000000010940fab7 _ZNK5dyld46Loader23runInitializersBottomUpERNS_12RuntimeStateERN5dyld35ArrayIPKS0_EE + 179
	14  dyld                                0x000000010940faa5 _ZNK5dyld46Loader23runInitializersBottomUpERNS_12RuntimeStateERN5dyld35ArrayIPKS0_EE + 161
	15  dyld                                0x000000010940faa5 _ZNK5dyld46Loader23runInitializersBottomUpERNS_12RuntimeStateERN5dyld35ArrayIPKS0_EE + 161
	16  dyld                                0x000000010940faa5 _ZNK5dyld46Loader23runInitializersBottomUpERNS_12RuntimeStateERN5dyld35ArrayIPKS0_EE + 161
	17  dyld                                0x000000010940fb60 _ZNK5dyld46Loader38runInitializersBottomUpPlusUpwardLinksERNS_12RuntimeStateE + 102
	18  dyld                                0x000000010941eb5a _ZN5dyld44APIs25runAllInitializersForMainEv + 222
	19  dyld                                0x00000001094029fe _ZN5dyld4L7prepareERNS_4APIsEPKN5dyld313MachOAnalyzerE + 2528
	20  dyld                                0x0000000109402e42 _dyld_sim_prepare + 379
	21  ???                                 0x0000000200ce5b24 0x0 + 8603458340
	22  ???                                 0x0000000200ce46de 0x0 + 8603453150
	23  ???                                 0x0000000200ce44b4 0x0 + 8603452596
	24  ???                                 0x0000000200cdf000 0x0 + 8603430912
)
libc++abi: terminating with uncaught exception of type NSException
```

**Environment**

**Steps to Reproduce Issue:**

1. Integrate the SDK using SwiftPM.
2. Create a Share Extension target.
3. Run Share Extension target from Xcode.

**Anything else:**

Related to issue #935

### PR DESCRIPTION
**Pull request by tony1224**
resolve #1073

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1074)

### CODE REVIEW

**Comment by emawby** [comment]
@tony1224 Thank you for your contribution. I have tested the branch and it seems to work, but I have not been able to validate that this fixes ShareExtensions. Can you explain your testing and how you came to this solution?

My other concern is making sure that this does not adversely affect Notification Service Extensions since OneSignal code needs to run in those App Extensions.

**Comment by jkasten2** [comment]
Initially I found it odd that an app extension would load the `UIApplication` class at all, I thought this is one of APIs that you can't access in an extension. After a closer look at Apple's `UIApplication.h` in XCode I noticed only some methods on the class have `NS_EXTENSION_UNAVAILABLE_IOS`. While most of it can't be used since you can't use `sharedApplication` anyway it doesn't mean something in the extension target isn't referencing it something that is triggering the loading of the `UIApplication` class.

`[UIApplication(OneSignal) load]` is being called definitely means that `UIApplication` was loaded into memory somehow, and given the above it is possible for this to happen. The code in `[UIApplication(OneSignal) load]` really don't need to be run in any app extension at all, so an early return to exclude `.appex` looks like a good approach to me.

**Review by jkasten2 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1074)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @emawby)

**Comment by jkasten2** [comment]
@emawby I approved it, give it one last look, approve it and merge it in if you agree.

**Pull request merged**
