### PR TITLE
SMS integration

### PR DESCRIPTION
**Pull request by Jeasmine**
SMS Integration

Emulates current channel email behavior, but in this case, for the new channel SMS.

Added setSMSNumber public function
Created new OSUserStateSMSSynchronizer
Implement new request methods under OSUserStateSMSSynchronizer to include SMS data
Create SMS observers
Include SMS data to the device state
All test are under SMSTests

Difference between SMS and email, not parent_player_id is sent, we relay on external_id

It is recommended to review commit by commit. The core implementation is done on the firsts commit, then on each test commit changes are made to make the feature truly work.

## 
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869)

### CODE REVIEW

**Review by emawby — CHANGES_REQUESTED** [review]
> Reviewed 26 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869)* status: 26 of 27 files reviewed, 2 unresolved discussions (waiting on @Jeasmine and @jkasten2)

___
*[iOS_SDK/OneSignalSDK/Source/OneSignal.h, line 398 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869#-MUkZ-jg8m6nf3gbSGY-:-MUkZ-jg8m6nf3gbSGY0:bf4ashc) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/28ee1b4b5e2df94611c50a917b5ad16927414dc9/iOS_SDK/OneSignalSDK/Source/OneSignal.h#L398)):*
> ```objc
>  * @return sms number if set, otherwise null
>  */
> @property (readonly, nullable) NSString* smsNumber;
> ```

Do we know what format the number will be in? It might be good to add it as a comment here if we do.
___
*[iOS_SDK/OneSignalSDK/Source/OSUserStateEmailSynchronizer.h, line 33 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869#-MUkaPwQCFd5GweXXAcC:-MUkaPwQCFd5GweXXAcD:b73r0tk) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/28ee1b4b5e2df94611c50a917b5ad16927414dc9/iOS_SDK/OneSignalSDK/Source/OSUserStateEmailSynchronizer.h#L33)):*
> ```objc
> 
> - (instancetype)initWithEmailSubscriptionState:(OSEmailSubscriptionState *)emailSubscriptionState
>                           withSubcriptionState:(OSSubscriptionState *)subscriptionState;
> ```

Why are we making this change on this PR?

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869)* status: all files reviewed, 8 unresolved discussions (waiting on @Jeasmine)

___
*[iOS_SDK/OneSignalSDK/Source/OneSignal.m, line 268 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869#-MUlnl-e-6Mz4WGDGPap:-MUlnl-e-6Mz4WGDGPaq:b-xtkj1w) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/28ee1b4b5e2df94611c50a917b5ad16927414dc9/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L268)):*
> ```objc
>     if (!_currentSMSSubscriptionState) {
>         _currentSMSSubscriptionState = [[OSSMSSubscriptionState alloc] init];
>         
> ```

nit, remove floating spaces on this line.
___
*[iOS_SDK/OneSignalSDK/Source/OneSignal.m, line 507 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869#-MUlobThBL-m-vTF9LPK:-MUlobThBL-m-vTF9LPL:b-xtkj1w) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/28ee1b4b5e2df94611c50a917b5ad16927414dc9/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L507)):*
> ```objc
>     self.currentSMSSubscriptionState.smsAuthCode = smsAuthToken;
>     [self.currentSMSSubscriptionState setSMSUserId:smsPlayerId];
>     
> ```

nit, remove floating spaces on this line.
___
*[iOS_SDK/OneSignalSDK/Source/OneSignal.m, line 510 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869#-MUloc1i44z0tTM3IM57:-MUloc1i44z0tTM3IM58:b-xtkj1w) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/28ee1b4b5e2df94611c50a917b5ad16927414dc9/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L510)):*
> ```objc
>     //call persistAsFrom in order to save the smsNumber & playerId to NSUserDefaults
>     [self.currentSMSSubscriptionState persist];
>     
> ```

nit, remove floating spaces on this line.
___
*[iOS_SDK/OneSignalSDK/Source/OSSMSSubscription.m, line 124 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869#-MUlqIok31V9_ujwsruM:-MUlqIolAEHSgcDAksL3:b-hgxqbp) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/28ee1b4b5e2df94611c50a917b5ad16927414dc9/iOS_SDK/OneSignalSDK/Source/OSSMSSubscription.m#L124)):*
> ```objc
>     stateChanges.to = [state copy];
>     
>     // wants OSSMSSubscriptionState
> ```

I don't understand this comment.
___
*[iOS_SDK/OneSignalSDK/Source/OSUserStateEmailSynchronizer.m, line 45 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869#-MUlwEsf6zdckIK6Arxr:-MUlwEsf6zdckIK6Arxs:b-29num0) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/28ee1b4b5e2df94611c50a917b5ad16927414dc9/iOS_SDK/OneSignalSDK/Source/OSUserStateEmailSynchronizer.m#L45)):*
> ```objc
>                           withSubcriptionState:(OSSubscriptionState *)subscriptionState {
>     self = [super init];
>     if (self){
> ```

nit, space between `)[`
___
*[iOS_SDK/OneSignalSDK/Source/Requests.m, line 167 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869#-MUm35Fv9_jM9RsZsymz:-MUm35Fv9_jM9RsZsyn-:bi70yjt) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/28ee1b4b5e2df94611c50a917b5ad16927414dc9/iOS_SDK/OneSignalSDK/Source/Requests.m#L167)):*
> ```objc
>     
>     if (smsNumber)
>         params[SMS_NUMBER_KEY] = smsNumber;
> ```

We shouldn't need this extra sms_number field as the `identifier` should be the sms number.

**Review by Jeasmine — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869)* status: all files reviewed, 5 unresolved discussions (waiting on @Jeasmine and @jkasten2)

___
*[iOS_SDK/OneSignalSDK/Source/OneSignal.m, line 268 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869#-MUlnl-e-6Mz4WGDGPap:-MV2xQvO8Nugzi0pprqB:bb7f2mf) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/28ee1b4b5e2df94611c50a917b5ad16927414dc9/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L268)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

nit, remove floating spaces on this line.
</blockquote></details>

done
___
*[iOS_SDK/OneSignalSDK/Source/OneSignal.m, line 507 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869#-MUlobThBL-m-vTF9LPK:-MV2xe5U1eARiTrgRXqB:bb7f2mf) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/28ee1b4b5e2df94611c50a917b5ad16927414dc9/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L507)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

nit, remove floating spaces on this line.
</blockquote></details>

done
___
*[iOS_SDK/OneSignalSDK/Source/OneSignal.m, line 510 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869#-MUloc1i44z0tTM3IM57:-MV2xoOU3idnny51Bf9T:bb7f2mf) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/28ee1b4b5e2df94611c50a917b5ad16927414dc9/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L510)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

nit, remove floating spaces on this line.
</blockquote></details>

done
___
*[iOS_SDK/OneSignalSDK/Source/OSSMSSubscription.m, line 124 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869#-MUlqIok31V9_ujwsruM:-MV2xpTC9p2wMxUdxyu4:b-h5yvdv) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/28ee1b4b5e2df94611c50a917b5ad16927414dc9/iOS_SDK/OneSignalSDK/Source/OSSMSSubscription.m#L124)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

I don't understand this comment.
</blockquote></details>

removed since not longer valid

**Review by Jeasmine — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869)* status: 24 of 28 files reviewed, 4 unresolved discussions (waiting on @emawby and @jkasten2)

___
*[iOS_SDK/OneSignalSDK/Source/OneSignal.h, line 398 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869#-MUkZ-jg8m6nf3gbSGY-:-MV38NSa4QzoP6uHdr5q:bzapgnp) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/28ee1b4b5e2df94611c50a917b5ad16927414dc9/iOS_SDK/OneSignalSDK/Source/OneSignal.h#L398)):*
<details><summary><i>Previously, emawby (Elliot Mawby) wrote…</i></summary><blockquote>

Do we know what format the number will be in? It might be good to add it as a comment here if we do.
</blockquote></details>

I checked again, backend matches to the following phone_number.match(/^\+[1-9]\d{1,14}$/). so I will add the format to the comment, nice catch!
___
*[iOS_SDK/OneSignalSDK/Source/OSSMSSubscription.m, line 124 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869#-MUlqIok31V9_ujwsruM:-MV3FLCO2GYLpodmyNaG:b-896fix) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/28ee1b4b5e2df94611c50a917b5ad16927414dc9/iOS_SDK/OneSignalSDK/Source/OSSMSSubscription.m#L124)):*
<details><summary><i>Previously, Jeasmine (JNahui) wrote…</i></summary><blockquote>

removed since not longer valid
</blockquote></details>

Done.
___
*[iOS_SDK/OneSignalSDK/Source/OSUserStateEmailSynchronizer.h, line 33 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869#-MUkaPwQCFd5GweXXAcC:-MV3Fj9E2kXINGbeG2xG:b-4ntd3h) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/28ee1b4b5e2df94611c50a917b5ad16927414dc9/iOS_SDK/OneSignalSDK/Source/OSUserStateEmailSynchronizer.h#L33)):*
<details><summary><i>Previously, emawby (Elliot Mawby) wrote…</i></summary><blockquote>

Why are we making this change on this PR?
</blockquote></details>

Because external id auth token is needed, check getExternalIdAuthHashToken method
___
*[iOS_SDK/OneSignalSDK/Source/OSUserStateEmailSynchronizer.m, line 45 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869#-MUlwEsf6zdckIK6Arxr:-MV3FsSX1ckdHuv7zm75:bb6un1j) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/28ee1b4b5e2df94611c50a917b5ad16927414dc9/iOS_SDK/OneSignalSDK/Source/OSUserStateEmailSynchronizer.m#L45)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

nit, space between `)[`
</blockquote></details>

Done
___
*[iOS_SDK/OneSignalSDK/Source/Requests.m, line 167 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869#-MUm35Fv9_jM9RsZsymz:-MV3P-8B6D_9fu2BtdqF:b-uyihef) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/28ee1b4b5e2df94611c50a917b5ad16927414dc9/iOS_SDK/OneSignalSDK/Source/Requests.m#L167)):*
> ```
>    params[SMS_NUMBER_KEY] = smsNumber;
> ```
nice catch!

**Review by jkasten2 — APPROVED** [review]
> Reviewed 4 of 4 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/869)* status: all files reviewed, 2 unresolved discussions (waiting on @emawby)

**Review by emawby — APPROVED** [review]

**Pull request merged**
