### PR TITLE
Adding Collapse id to OSNotification

### PR DESCRIPTION
**Pull request by emawby**
# Description
## One Line Summary
Adding a readonly string property `collapseId` to the public `OSNotification` object and populating it with the collapseId set on a notification.

## Details
The collapse id field is set to the [request.identifier field](https://developer.apple.com/documentation/usernotifications/unnotificationrequest/1649634-identifier?language=objc) when a notification is received.

In order to parse it to OSNotification both inside and outside the service extension I am adding the value of this field to the notification's content.userInfo dictionary from the `OneSignalNotificationServiceExtensionHandler`'s `didReceiveNotificationExtensionRequest: withMutableNotificationContent:` method. 

I am adding the value to the key `collapse_id` to the `custom` or `os_data` dictionary depending on which format the notification is using.

### Motivation
We currently have collapseId on Android's OSNotification object but not on iOS. This field is in the iOS notification request's identifier field so we can add it to OSNotification without any backend changes.

### Scope
This change involves adding a new readonly string field to the **public** OSNotification object called `collapseId`.

# Testing
## Unit testing
✅  All tests pass after the below modifications
Added unit tests for parsing the collapse id from request.identifier and adding it to either os_data or custom depending on which format the notification is using.

## Manual testing
✅  Tested on an iOS device from both send to test user and a real notification.

### Example of the Result
setting the collapse id on the dashboard/api will populate collapseId in the OSNotification object

# Affected code checklist
   - [x] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [x] Public API changes

# Checklist
## Overview
   - [x] I have filled out all **REQUIRED** sections above
   - [X] PR does one thing
   - [X] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [x] I have included test coverage for these changes, or explained why they are not needed
   - [x] All automated tests pass, or I explained why that is not possible
   - [X] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [X] Code is as readable as possible.
   - [x] I have reviewed this PR myself, ensuring it meets each checklist item

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1024)

### CODE REVIEW

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1024)* status: all files reviewed, 2 unresolved discussions (waiting on @emawby and @nan-li)

___
*[iOS_SDK/OneSignalSDK/Source/OneSignalNotificationServiceExtensionHandler.m, line 59 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1024#-MooNRJE4-0O86REMFnW:-MooNRJE4-0O86REMFnX:bgk46l8) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/c5629b93d7b2f2f1478d4db08bccdf057a2d24d1/iOS_SDK/OneSignalSDK/Source/OneSignalNotificationServiceExtensionHandler.m#L59)):*
> ```objc
>     
>     /*
>         Add the collapse Id (request.identifier) to userInfo
> ```

Would be clearer if this was in it's own method.
___
*[iOS_SDK/OneSignalSDK/UnitTests/UnitTests.m, line 3394 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1024#-MooNZwk6D-674QP2ycR:-MooNZwk6D-674QP2ycS:b9zz8pq) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/c5629b93d7b2f2f1478d4db08bccdf057a2d24d1/iOS_SDK/OneSignalSDK/UnitTests/UnitTests.m#L3394)):*
> ```objc
>     #pragma clang diagnostic push
>     #pragma clang diagnostic ignored "-Wdeprecated-declarations"
>     UNMutableNotificationContent* content = [OneSignal didReceiveNotificationExtensionRequest:[notifResponse notification].request withMutableNotificationContent:nil];
> ```

Would be it easy to use the new method so we don't have to use `deprecated-declarations`?

**Review by emawby — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1024)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @jkasten2 and @nan-li)

___
*[iOS_SDK/OneSignalSDK/Source/OneSignalNotificationServiceExtensionHandler.m, line 59 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1024#-MooNRJE4-0O86REMFnW:-MooUM3hAdDnoLHJMJSL:b-896fix) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/c5629b93d7b2f2f1478d4db08bccdf057a2d24d1/iOS_SDK/OneSignalSDK/Source/OneSignalNotificationServiceExtensionHandler.m#L59)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Would be clearer if this was in it's own method.
</blockquote></details>

Done.
___
*[iOS_SDK/OneSignalSDK/UnitTests/UnitTests.m, line 3394 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1024#-MooNZwk6D-674QP2ycR:-MooSKLt2OBXG2X0-Dnc:b-896fix) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/c5629b93d7b2f2f1478d4db08bccdf057a2d24d1/iOS_SDK/OneSignalSDK/UnitTests/UnitTests.m#L3394)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Would be it easy to use the new method so we don't have to use `deprecated-declarations`?
</blockquote></details>

Done.

**Review by jkasten2 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1024)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nan-li)

**Review by jkasten2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1024#-:-MooXwrhEBHsdWJU5oDE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nan-li)

**Review by nan-li — APPROVED** [review]

**Pull request merged**
