### PR TITLE
iOS 12

### PR DESCRIPTION
**Pull request by Nightsd01**
• Adds the new provisional/direct-to-history user notification authorization
• This can be controlled with the iOS parameters downloaded from OneSignal (will be enabled by a configuration for your app)
• If you enable Provisional notifications, users will be immediately subscribed for provisional notifications, you can still call `promptForPushNotificationsWithUserResponse` to show a traditional push notification permission dialog.
• If you enable Provisional notifications, users will be immediately subscribed for provisional notifications, you can still call `promptForPushNotificationsWithUserResponse` to show a traditional push notification permission dialog.
• New tests for provisional notifications will only execute in the Xcode 10 beta, and will not run in earlier versions of Xcode (ie. Travis), where they will simply show up as 'passed'. 

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379)

### CODE REVIEW

**Comment by jkasten2** [comment]
Reviewed 2 of 21 files at r1.
Review status: 2 of 21 files reviewed, 8 unresolved discussions (waiting on @Nightsd01 and @jkasten2)

---

*[iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m, line 75 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379#-LFcuZV-9Vuo6TSNphxm:-LFcuZV-9Vuo6TSNphxn:b-oc0r89) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/6f711c6d5b6174ab25d76f4210ca5c551fd104d1/iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m#L75)):*
> ```objc
>             status.provisional = (settings.authorizationStatus == 3);
>             status.accepted = settings.authorizationStatus == UNAuthorizationStatusAuthorized && !status.provisional;
>             NSLog(@"Status authorization: %d %d", (settings.authorizationStatus == UNAuthorizationStatusAuthorized), status.provisional);
> ```

Use `onesignal_Log` instead of `NSLog`

---

*[iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m, line 83 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379#-LFcv9Fe2l6wJ-soPcBi:-LFcv9Fe2l6wJ-soPcBj:b-cfoqt4) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/6f711c6d5b6174ab25d76f4210ca5c551fd104d1/iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m#L83)):*
> ```objc
>             if (@available(iOS 12, *))
>                 if (status.notificationTypes == 0 && settings.authorizationStatus == provisionalStatus)
>                     status.notificationTypes = 1;
> ```

Instead of updating this inline here it would be better to add this to `getNotificationTypes` so this the the source of truth for this value

---

*[iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m, line 120 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379#-LFdUn7T1psAsL4lwoer:-LFcvVbuE04LP3Xjaooq:buzc95w) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/6f711c6d5b6174ab25d76f4210ca5c551fd104d1/iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m#L120)):*
> ```objc
>         // Run callback on main / UI thread
>         [OneSignalHelper dispatch_async_on_main_queue: ^{
>             OneSignal.currentPermissionState.provisional = false;
> ```

This should be `true` if granted, since provisional is inclusive with accepted.

---

*[iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m, line 137 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379#-LFdBjVA-2pBXI47Qvjz:-LFdBjVA-2pBXI47Qvk-:b-c4i2u5) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/6f711c6d5b6174ab25d76f4210ca5c551fd104d1/iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m#L137)):*
> ```objc
> }
> 
> - (void)registerForProvisionalAuthorization:(void(^)(BOOL accepted))completionHandler {
> ```

Looks like `completionHandler` is unused. Can we drop this then?

---

*[iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m, line 139 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379#-LFdTqGaDlr4m9OqT-1x:-LFdTqGaDlr4m9OqT-1y:brn3ows) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/6f711c6d5b6174ab25d76f4210ca5c551fd104d1/iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m#L139)):*
> ```objc
> - (void)registerForProvisionalAuthorization:(void(^)(BOOL accepted))completionHandler {
>     
>     if (@available(iOS 12, *)) {
> ```

A return early flow will be easier to read.

---

*[iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m, line 157 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379#-LFdBHDx2lMNhtziMcf5:-LFdBHDy8BgqBJtXPM8I:b6tgq60) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/6f711c6d5b6174ab25d76f4210ca5c551fd104d1/iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m#L157)):*
> ```objc
>         };
>         
>         [center requestAuthorizationWithOptions:(UNAuthorizationOptions)(1 << 6) completionHandler:responseBlock];
> ```

Would be easier to read if we create our own const for this instead of using ` 1 << 6`

---

*[iOS_SDK/OneSignalSDK/Source/UNUserNotificationCenter+OneSignal.m, line 109 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379#-LFdVQ9r2IWFjb7uPkWn:-LFdVQ9r2IWFjb7uPkWo:b-wf0t1b) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/6f711c6d5b6174ab25d76f4210ca5c551fd104d1/iOS_SDK/OneSignalSDK/Source/UNUserNotificationCenter+OneSignal.m#L109)):*
> ```objc
>         if (provisionalRequest) {
>             OneSignal.currentPermissionState.accepted = granted;
>             OneSignal.currentPermissionState.answeredPrompt = true;
> ```

`provisional` should NOT have an effect on `answeredPrompt`

---

*[iOS_SDK/OneSignalSDK/UnitTests/ProvisionalAuthorizationTests.m, line 6 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379#-LFdVZkk2wlffQWTTXU_:-LFdVZkk2wlffQWTTXUa:b-lp5wk6) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/6f711c6d5b6174ab25d76f4210ca5c551fd104d1/iOS_SDK/OneSignalSDK/UnitTests/ProvisionalAuthorizationTests.m#L6)):*
> ```objc
> //
> //  Created by Brad Hesse on 6/19/18.
> //  Copyright © 2018 Hiptic. All rights reserved.
> ```

Update header to OneSignal

---


*Comments from [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379)*

**Comment by Nightsd01** [comment]
*[iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m, line 120 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379#-LFdUn7T1psAsL4lwoer:-LFddRrb9Zt5ct8Hmml-:bpemx10) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/6f711c6d5b6174ab25d76f4210ca5c551fd104d1/iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m#L120)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

This should be `true` if granted, since provisional is inclusive with accepted.
</blockquote></details>

Discussed this and determined that it is exclusive, whether the user accepts/denies the prompt, provisional will be false

---


*Comments from [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379)*

**Comment by Nightsd01** [comment]
*[iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m, line 83 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379#-LFcv9Fe2l6wJ-soPcBi:-LFddOR2AwCaOh5OV_jD:b-896fix) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/6f711c6d5b6174ab25d76f4210ca5c551fd104d1/iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m#L83)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Instead of updating this inline here it would be better to add this to `getNotificationTypes` so this the the source of truth for this value
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379)*

**Comment by Nightsd01** [comment]
*[iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m, line 75 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379#-LFcuZV-9Vuo6TSNphxm:-LFddOra4B42fcsfN13C:b-896fix) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/6f711c6d5b6174ab25d76f4210ca5c551fd104d1/iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m#L75)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Use `onesignal_Log` instead of `NSLog`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379)*

**Comment by Nightsd01** [comment]
*[iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m, line 139 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379#-LFdTqGaDlr4m9OqT-1x:-LFde61I9m_MXDrEhRdw:bfk4wy0) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/6f711c6d5b6174ab25d76f4210ca5c551fd104d1/iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m#L139)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

A return early flow will be easier to read.
</blockquote></details>

Switched to an early return and also switched to using the `[OneSignalHelper isIOSVersionGreatherOrEqual:]` method to be more consistent

---


*Comments from [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379)*

**Comment by Nightsd01** [comment]
*[iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m, line 157 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379#-LFdBHDx2lMNhtziMcf5:-LFdewmM9_Z-XT6HxSp-:b-gwoo75) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/6f711c6d5b6174ab25d76f4210ca5c551fd104d1/iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m#L157)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Would be easier to read if we create our own const for this instead of using ` 1 << 6`
</blockquote></details>

Good idea, replaced with a macro defined in our Common Defines header (`PROVISIONAL_UNAUTHORIZATIONOPTION`)

---


*Comments from [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379)*

**Comment by Nightsd01** [comment]
*[iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m, line 137 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379#-LFdBjVA-2pBXI47Qvjz:-LFdp63UBVGQ175T65gU:bfvjlp6) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/6f711c6d5b6174ab25d76f4210ca5c551fd104d1/iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m#L137)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Looks like `completionHandler` is unused. Can we drop this then?
</blockquote></details>

We decided to make this a public method so the completion handler is useful

---


*Comments from [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379)*

**Comment by Nightsd01** [comment]
*[iOS_SDK/OneSignalSDK/UnitTests/ProvisionalAuthorizationTests.m, line 6 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379#-LFdVZkk2wlffQWTTXU_:-LFdpGgZ835-l-OyY6bd:b-896fix) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/6f711c6d5b6174ab25d76f4210ca5c551fd104d1/iOS_SDK/OneSignalSDK/UnitTests/ProvisionalAuthorizationTests.m#L6)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Update header to OneSignal
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379)*

**Comment by Nightsd01** [comment]
*[iOS_SDK/OneSignalSDK/Source/UNUserNotificationCenter+OneSignal.m, line 109 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379#-LFdVQ9r2IWFjb7uPkWn:-LFdpjxS9pQ_0s6kValy:bxd1gyg) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/6f711c6d5b6174ab25d76f4210ca5c551fd104d1/iOS_SDK/OneSignalSDK/Source/UNUserNotificationCenter+OneSignal.m#L109)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

`provisional` should NOT have an effect on `answeredPrompt`
</blockquote></details>

`provisionalRequest` was named a bit confusingly. Renamed to `notProvisionalRequest`

---


*Comments from [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379)*

**Comment by jkasten2** [comment]
Reviewed 13 of 21 files at r1, 8 of 8 files at r2.
Review status: all files reviewed, 4 unresolved discussions (waiting on @jkasten2 and @Nightsd01)

---

*[iOS_SDK/OneSignalSDK/Source/OneSignal.m, line 671 at r2](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379#-LFxancx9aIMHyAvIK6J:-LFxancx9aIMHyAvIK6K:b-4z0zis) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/4d76d05e8198156b2fbbea427e1432f12333f1ed/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L671)):*
> ```objc
>         }
>         
>         //TODO: Determine if the autoprompt setting overrides this.
> ```

Right, auto prompting should override the provisional.

---

*[iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m, line 139 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379#-LFdTqGaDlr4m9OqT-1x:-LFxbXk3-9uUzpi28cl0:b-4vv2x2) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/6f711c6d5b6174ab25d76f4210ca5c551fd104d1/iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m#L139)):*
<details><summary><i>Previously, Nightsd01 (Brad Hesse) wrote…</i></summary><blockquote>

Switched to an early return and also switched to using the `[OneSignalHelper isIOSVersionGreatherOrEqual:]` method to be more consistent
</blockquote></details>

`completionHandler` should still fire in this case with `false`.

---

*[iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m, line 149 at r2](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379#-LFxbcKZ03-hPalSLIS7:-LFxbcKZ03-hPalSLIS8:b-yi20j1) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/4d76d05e8198156b2fbbea427e1432f12333f1ed/iOS_SDK/OneSignalSDK/Source/OneSignalNotificationSettingsIOS10.m#L149)):*
> ```objc
>     //don't register for provisional if the user has already accepted the prompt
>     if (state.status != OSNotificationPermissionNotDetermined || state.answeredPrompt)
>         return;
> ```

`completionHandler` should fire with `true` in this case.

---


*Comments from [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379)*

**Comment by jkasten2** [comment]
Reviewed 2 of 2 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379)*

**Comment by jkasten2** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/379#-:-LFyNfqk1dZ9DKiVBl5K:bnfp4nl)*

**Pull request merged**
