### PR TITLE
Extension Badge Handling

### PR DESCRIPTION
**Pull request by Nightsd01**
• Moves badge increment/decrement logic from the OneSignal backend to the application itself
• This is accomplished using an app extension with an 'app group' to allow communication of data between the host app and it's notification extension service
• This allows the app to maintain a consistent badge count
• Also cleaned up some Firebase code and moved common strings to a definitions file
• Changed the SDK so that it will default to group.{bundle_id}.onesignal as the App Group name if one is not provided in Info.plist

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/352)

### CODE REVIEW

**Comment by jkasten2** [comment]
Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[iOS_SDK/OneSignalSDK/Source/OneSignalExtensionBadgeHandler.h, line 6 at r1](https://reviewable.io:443/reviews/onesignal/onesignal-ios-sdk/352#-L8E1cUSmun4kqaCSs_D:-L8E1cUSmun4kqaCSs_E:b-98z5be) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/467be7ac9dd9ae21d5e5006179f504ec99734f1f/iOS_SDK/OneSignalSDK/Source/OneSignalExtensionBadgeHandler.h#L6)):*
> ```objc
> //
> //  Created by Brad Hesse on 3/15/18.
> //  Copyright © 2018 Hiptic. All rights reserved.
> ```

Fix copyright header

---

*[iOS_SDK/OneSignalSDK/Source/OneSignalExtensionBadgeHandler.m, line 6 at r2](https://reviewable.io:443/reviews/onesignal/onesignal-ios-sdk/352#-L8Ede9PnVEjwXSeh-4G:-L8Ede9PnVEjwXSeh-4H:b-98z5be) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/56bbcb540942dd5421a3b5483172b045cec6847c/iOS_SDK/OneSignalSDK/Source/OneSignalExtensionBadgeHandler.m#L6)):*
> ```objc
> //
> //  Created by Brad Hesse on 3/15/18.
> //  Copyright © 2018 Hiptic. All rights reserved.
> ```

Fix copyright header

---

*[iOS_SDK/OneSignalSDK/UnitTests/UnitTests.m, line 1835 at r2](https://reviewable.io:443/reviews/onesignal/onesignal-ios-sdk/352#-L8EcfLVGHANxxzRJZY3:-L8EcfLVGHANxxzRJZY4:b-cgk33a) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/56bbcb540942dd5421a3b5483172b045cec6847c/iOS_SDK/OneSignalSDK/UnitTests/UnitTests.m#L1835)):*
> ```objc
>             @"att": @{ @"id": @"http://domain.com/file.jpg" }
>         },
>         @"badge_inc" : @3
> ```

`badge_inc` should be under `os_data` or `custom` depending on the payload type. Otherwise this is going to end up in additional data when `os_data` is the format type.

---

*[iOS_SDK/OneSignalSDK/UnitTests/UnitTests.m, line 1854 at r2](https://reviewable.io:443/reviews/onesignal/onesignal-ios-sdk/352#-L8Ed9hMoXAkSACmVLSN:-L8Ed9hMoXAkSACmVLSO:bnfk3qo) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/56bbcb540942dd5421a3b5483172b045cec6847c/iOS_SDK/OneSignalSDK/UnitTests/UnitTests.m#L1854)):*
> ```objc
>     XCTAssert([(NSNumber *)[defaults objectForKey:ONESIGNAL_BADGE_KEY] isEqualToNumber:@2]);
> }
> ```

Can we add an 2nd notification service extension service that the NSDefault is se when aps `badge` is set but `badge_inc` is not present?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/onesignal/onesignal-ios-sdk/352)*

**Comment by Nightsd01** [comment]
*[iOS_SDK/OneSignalSDK/Source/OneSignalExtensionBadgeHandler.h, line 6 at r1](https://reviewable.io:443/reviews/onesignal/onesignal-ios-sdk/352#-L8E1cUSmun4kqaCSs_D:-L8Exl4hJLZcyWNqFJL-:b-21fh8j) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/467be7ac9dd9ae21d5e5006179f504ec99734f1f/iOS_SDK/OneSignalSDK/Source/OneSignalExtensionBadgeHandler.h#L6)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Fix copyright header
</blockquote></details>

Fixed in multiple files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/onesignal/onesignal-ios-sdk/352)*

**Comment by Nightsd01** [comment]
*[iOS_SDK/OneSignalSDK/UnitTests/UnitTests.m, line 1854 at r2](https://reviewable.io:443/reviews/onesignal/onesignal-ios-sdk/352#-L8Ed9hMoXAkSACmVLSN:-L8Ey4bCI0aTb1OAqgp9:bs42rq4) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/56bbcb540942dd5421a3b5483172b045cec6847c/iOS_SDK/OneSignalSDK/UnitTests/UnitTests.m#L1854)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Can we add an 2nd notification service extension service that the NSDefault is se when aps `badge` is set but `badge_inc` is not present?
</blockquote></details>

Moved the new badge tests to `BadgeTests.m`, added this as a test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/onesignal/onesignal-ios-sdk/352)*

**Comment by jkasten2** [comment]
Reviewed 3 of 9 files at r1, 17 of 17 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/onesignal/onesignal-ios-sdk/352)*

**Comment by jkasten2** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/onesignal/onesignal-ios-sdk/352#-:-L8F1VHmwC14c6x9UmAD:bnfp4nl)*

**Pull request merged**
