### PR TITLE
[User model] Send location on properties model

### PR DESCRIPTION
**Pull request by emawby**
# Description
## One Line Summary
This PR uses OneSignalLocation to set the lat and long values on the properties model

## Details
Added setLocation to the user manager and removed outcomes/triggers from the user interface. 
I am using `latitude` and `longitude` as the parameter names for objc facing methods since `long` is a keyword that Xcode wasn't happy about. 

### Motivation
Get location working with user model

### Scope
Location code and removing outdated code

# Testing
## Unit testing
added a very basic unit test, but unit tests don't run currently

## Manual testing
tested by running the example app

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [x] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [x] I have filled out all **REQUIRED** sections above
   - [x] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [x] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [x] I have included test coverage for these changes, or explained why they are not needed
   - [x] All automated tests pass, or I explained why that is not possible
   - [x] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [x] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [x] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

- - -
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1177)

### CODE REVIEW

**Review by fhboswell — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1177#-:-NIoLBPK0mINFd_7SLb_:bnfp4nl)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @jennantilla, @jkasten2, and @nan-li)

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1177)* status: all files reviewed, 2 unresolved discussions (waiting on @emawby, @jennantilla, and @nan-li)

___
*[`iOS_SDK/OneSignalSDK/OneSignalUser/Source/OSPropertiesModel.swift` line 41 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1177#-NIoLaKsCNpHQjORR4E9:-NIoLaKsCNpHQjORR4EA:bioqjda) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/d70d0dd0476191b53eb60849c88bdba3aec85cb1/iOS_SDK/OneSignalSDK/OneSignalUser/Source/OSPropertiesModel.swift#L41)):*
> ```Swift
>     var lat: Float? {
>         didSet {
>             print("🔥 didSet OSPropertiesModel.lat from \(oldValue ?? 0) to \(lat ?? 0).")
> ```

Remove print or use OneSignal logger
___
*[`iOS_SDK/OneSignalSDK/OneSignalUser/Source/OSPropertiesModel.swift` line 48 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1177#-NIoLdm87KpcEh1Se1ev:-NIoLdm87KpcEh1Se1ew:bioqjda) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/d70d0dd0476191b53eb60849c88bdba3aec85cb1/iOS_SDK/OneSignalSDK/OneSignalUser/Source/OSPropertiesModel.swift#L48)):*
> ```Swift
>     var long: Float? {
>         didSet {
>             print("🔥 didSet OSPropertiesModel.long from \(oldValue ?? 0) to \(long ?? 0).")
> ```

Remove print or use OneSignal logger

**Review by emawby — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1177)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @jennantilla, @jkasten2, and @nan-li)

___
*[`iOS_SDK/OneSignalSDK/OneSignalUser/Source/OSPropertiesModel.swift` line 41 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1177#-NIoLaKsCNpHQjORR4E9:-NIoWZCz7oAH3D6_qVht:b-896fix) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/d70d0dd0476191b53eb60849c88bdba3aec85cb1/iOS_SDK/OneSignalSDK/OneSignalUser/Source/OSPropertiesModel.swift#L41)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Remove print or use OneSignal logger
</blockquote></details>

Done.
___
*[`iOS_SDK/OneSignalSDK/OneSignalUser/Source/OSPropertiesModel.swift` line 48 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1177#-NIoLdm87KpcEh1Se1ev:-NIoW_h021ETVq3G54XO:b-896fix) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/d70d0dd0476191b53eb60849c88bdba3aec85cb1/iOS_SDK/OneSignalSDK/OneSignalUser/Source/OSPropertiesModel.swift#L48)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Remove print or use OneSignal logger
</blockquote></details>

Done.

**Review by jkasten2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1177#-:-NIof1p12SijbMWEXPL-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jennantilla and @nan-li)

**Pull request merged**
