### PR TITLE
Launch url suppress

### PR DESCRIPTION
**Pull request by gonzalonarbaiz**
Added method to override behavior. 
_There are several commits prior to the actual implementation._

## 
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/867)

### CODE REVIEW

**Comment by emawby** [comment]
Looks good can you rebase to clean up the commit history before merging?

**Review by emawby — CHANGES_REQUESTED** [review]
waiting for commit history cleanup

**Review by emawby — CHANGES_REQUESTED** [review]
still waiting on fixup

**Comment by gonzalonarbaiz** [comment]
> still waiting on fixup

**Review by emawby — APPROVED** [review]

**Pull request merged**
