### PR TITLE
Fix Email and SMS channel being overridden by Push Channel

### PR DESCRIPTION
**Pull request by Jeasmine**
* Delete notification_types param from email requests
* Remove notification_types from email request test
* Remove notification_types param from sms request
* Remove notification_types from tests
* Remove notification_types from SMS and Email on_session request

### Problem
notification_types params were being sent on all channel requests. This ended on Email and Push subscription to have notification type on Dashboard.

### Result
Removing notification_types from SMS and Email updates solved the problem. The subscription type on the dashboard is not affected by the push notification_type.

Tested with iOS 12.3 

## 
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/899)

### CODE REVIEW

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/899)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @emawby, @Jeasmine, and @jkasten2)

___
*[iOS_SDK/OneSignalSDK/Source/Requests.m, line 128 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/899#-MVppThw8NPD2wJGlYte:-MVppThw8NPD2wJGlYtf:b-dnqyr0) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/b969e10a0bf4486a06de0bb6f0443329724b5e0c/iOS_SDK/OneSignalSDK/Source/Requests.m#L128)):*
> ```objc
> 
> @implementation OSRequestUpdateDeviceToken
> + (instancetype _Nonnull)withUserId:(NSString * _Nonnull)userId appId:(NSString * _Nonnull)appId deviceToken:(NSString * _Nullable)identifier notificationTypes:(NSNumber * _Nullable)notificationTypes externalIdAuthToken:(NSString * _Nullable)externalIdAuthToken {
> ```

It looks like we have two methods on `OSRequestUpdateDeviceToken` now. It is isn't clear what each is for right away, could we add a comment to each what they are for? (one to update push, the other to update other channels)

**Review by Jeasmine — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/899)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @emawby and @jkasten2)

___
*[iOS_SDK/OneSignalSDK/Source/Requests.m, line 128 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/899#-MVppThw8NPD2wJGlYte:-MVrVAGo-cZerXrci3NM:b-896fix) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/b969e10a0bf4486a06de0bb6f0443329724b5e0c/iOS_SDK/OneSignalSDK/Source/Requests.m#L128)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

It looks like we have two methods on `OSRequestUpdateDeviceToken` now. It is isn't clear what each is for right away, could we add a comment to each what they are for? (one to update push, the other to update other channels)
</blockquote></details>

Done.

**Review by emawby — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/899)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @emawby and @jkasten2)

**Review by jkasten2 — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/899)* status: 12 of 13 files reviewed, all discussions resolved (waiting on @jkasten2)

**Review by jkasten2 — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/899)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Jeasmine)

**Comment by Jeasmine** [comment]
Already rebased with feature/sms-integration

**Pull request closed without merging**
