### PR TITLE
Don't escape slashes on PUTs

### PR DESCRIPTION
**Pull request by adamschlesinger**
Resolves https://app.asana.com/0/1193807006058450/1201230887422941/f

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1015)

### CODE REVIEW

**Review by jkasten2 — CHANGES_REQUESTED** [review]
Ah nice find, ya no point in doing `NSJSONWritingPrettyPrinted` for the network request so we can remove it.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1015#-:-MnCQLo54NJSaV0oxDdA:b-ggrq64)* status: all files reviewed, 1 unresolved discussion (waiting on @adamschlesinger, @emawby, @jmadler, and @nan-li)

___
*[iOS_SDK/OneSignalSDK/Source/OneSignalRequest.m, line 104 at r2](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1015#-MnCPPtM2oxk-siqHOE8:-MnCPPtM2oxk-siqHOE9:b96elf2) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/dd6fbf62e7d23d4920fd1da68232e924ee7b3615/iOS_SDK/OneSignalSDK/Source/OneSignalRequest.m#L104)):*
> ```objc
>     
>     NSError *error;
>     if (@available(iOS 13, *))
> ```

What do you think about having one implementation for all versions of iOS? We can add a code comment that we can switch to `NSJSONWritingWithoutEscapingSlashes` once the SDK makes iOS 13 the minimum required version?

My motivation for this it means if there is an issue it is easier to find the issue as it removes which version of iOS was used.

**Review by adamschlesinger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1015)* status: all files reviewed, 1 unresolved discussion (waiting on @emawby, @jkasten2, @jmadler, and @nan-li)

___
*[iOS_SDK/OneSignalSDK/Source/OneSignalRequest.m, line 104 at r2](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1015#-MnCPPtM2oxk-siqHOE8:-MnQzJGyAQW31YX-dB_2:b1aclm0) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/dd6fbf62e7d23d4920fd1da68232e924ee7b3615/iOS_SDK/OneSignalSDK/Source/OneSignalRequest.m#L104)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

What do you think about having one implementation for all versions of iOS? We can add a code comment that we can switch to `NSJSONWritingWithoutEscapingSlashes` once the SDK makes iOS 13 the minimum required version?

My motivation for this it means if there is an issue it is easier to find the issue as it removes which version of iOS was used.
</blockquote></details>

I'd rather have the code be "self healing". [Less than 10% of total iOS devices are under iOS13](https://developer.apple.com/support/app-store/). The actual active % is likely even smaller.

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1015)* status: all files reviewed, 1 unresolved discussion (waiting on @adamschlesinger, @emawby, @jmadler, and @nan-li)

___
*[iOS_SDK/OneSignalSDK/Source/OneSignalRequest.m, line 109 at r3](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1015#-Mo0ID8O2A81WilWCjP6:-Mo0ID8O2A81WilWCjP7:b-72mywp) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/64a38485fc9563a72a7ccf535341064a8ce55de8/iOS_SDK/OneSignalSDK/Source/OneSignalRequest.m#L109)):*
> ```objc
>     NSRegularExpression *eidRegex = [NSRegularExpression regularExpressionWithPattern:@"(?<=\"external_user_id\":\").*\\/.*?(?=\",|\"\\})" options:0 error:&error];
>     NSArray *matches = [eidRegex matchesInString:requestString options:0 range:NSMakeRange(0, [requestString length])];
>     for (NSTextCheckingResult *match in matches) {
> ```

In Android we grab index 0 on matches. Is there are reason why this implementation is different? Can we make the two SDKs the same?

**Review by jkasten2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1015#-:-Mo5Bq-81XqFQXBhJT-V:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @adamschlesinger, @emawby, @jmadler, and @nan-li)

**Review by emawby — APPROVED** [review]

**Pull request merged**
