### PR TITLE
Major release 3.0.0 beta4 cut

### PR DESCRIPTION
**Pull request by emawby**
This PR is for the beta 4 cut of the 3.0 Major Release. It will not actually merge into master. Please verify the version numbers are correct in OneSignal.m and the podspecs and ensure that the OneSignal.h headers look correct

## 
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/807)

### CODE REVIEW

**Comment by emawby** [comment]
The unit tests pass locallay

**Comment by jkasten2** [comment]
Github says `major_release_3.0.0-beta4-cut` is 13 commit behind master and has merge conflicts with `iOS_SDK/OneSignalSDK/Source/OneSignal.m` and `iOS_SDK/OneSignalSDK/Source/OneSignal.h`. However I checked a few of the last commits from master and the changes are in here for them so not sure what I missing or is the conflict.

**Comment by jkasten2** [comment]
Noticed this line is missing this branch that is in master
https://github.com/OneSignal/OneSignal-iOS-SDK/pull/745/files#diff-d5a48640d81279fceea25a2bb1138a95303c65f68e0fa7041817f470a2334106R1715

**Comment by emawby** [comment]
> Github says `major_release_3.0.0-beta4-cut` is 13 commit behind master and has merge conflicts with `iOS_SDK/OneSignalSDK/Source/OneSignal.m` and `iOS_SDK/OneSignalSDK/Source/OneSignal.h`. However I checked a few of the last commits from master and the changes are in here for them so not sure what I missing or is the conflict.

This is expected no? It should be compared to Major_Release_3.0.0 not master

**Comment by jkasten2** [comment]
Tests failing due to log length. Ok for this PR

**Review by jkasten2 — APPROVED** [review]

**Pull request closed without merging**
