### PR TITLE
Add logout SMS method

### PR DESCRIPTION
**Pull request by Jeasmine**
* Add logoutSMS() public method
* Add logout SMS request to OSStateSynchronizer
* Add logoutSMS tests

## 
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/875)

### CODE REVIEW

**Review by emawby — CHANGES_REQUESTED** [review]
The SMSTests are failing to build because the target membership is wrong. Unselect OneSignal and OneSignalFramework
image

**Comment by Jeasmine** [comment]
> The SMSTests are failing to build because the target membership is wrong. Unselect OneSignal and OneSignalFramework
> image

Nice catch! fixed on https://github.com/OneSignal/OneSignal-iOS-SDK/pull/869/commits/28ee1b4b5e2df94611c50a917b5ad16927414dc9 parent branch

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/875)* status: all files reviewed, 1 unresolved discussion (waiting on @Jeasmine)

___
*[iOS_SDK/OneSignalSDK/Source/Requests.m, line 255 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/875#-MUmELGpC1CGHM8Sq4j2:-MUmELGpC1CGHM8Sq4j3:bx0z4fc) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/ec184b5c175fbbc7553cac25aef44cde7d7b7163/iOS_SDK/OneSignalSDK/Source/Requests.m#L255)):*
> ```objc
>     
>     request.method = POST;
>     request.path = [NSString stringWithFormat:@"players/%@/sms_logout", devicePlayerId];
> ```

Backend won't have a `sms_logout` endpoint. The SDK will just stop updating the SMS record.

**Review by Jeasmine — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/875)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @jkasten2)

___
*[iOS_SDK/OneSignalSDK/Source/Requests.m, line 255 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/875#-MUmELGpC1CGHM8Sq4j2:-MV3Tb8D85g5cfSUgaj3:b-896fix) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/ec184b5c175fbbc7553cac25aef44cde7d7b7163/iOS_SDK/OneSignalSDK/Source/Requests.m#L255)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Backend won't have a `sms_logout` endpoint. The SDK will just stop updating the SMS record.
</blockquote></details>

Done.

**Review by Jeasmine — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/875)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @emawby and @jkasten2)

___
*[iOS_SDK/OneSignalSDK/Source/OSStateSynchronizer.m, line 263 at r2](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/875#-MVIE4yYE2VT2UH_cWWQ:-MVJPJ0f-IgxC9kGeW4W:b-nrio7f) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/bec7b9e7328b74421d0323985dd16a54469e41f6/iOS_SDK/OneSignalSDK/Source/OSStateSynchronizer.m#L263)):*
> ```
>  [self callSMSSuccessBlockOnMainThread:successBlock withSMSNumber:smsNumber];
> ```
This is for returning an object to the success callback and to avoid ending as we have on email, an empty success callback. If you remember we talked wide ago to always return something for wrappers to have something to read from. And also to keep it consistent between callbacks. Email will be the only one left with no returning objects

**Review by jkasten2 — APPROVED** [review]
> Reviewed 3 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/875)* status: all files reviewed, 1 unresolved discussion (waiting on @emawby)

**Review by emawby — APPROVED** [review]

**Pull request merged**
