### PR TITLE
update checksums

### LINKED ISSUE #1140: [Bug]: SwiftPM broken after last update
### What happened?

After the last update (3.11.4) SwiftPM installation fails with "invalid checksums" for all artifacts

### Steps to reproduce?

```Markdown
Add OneSignal-XCFramework to project via SwiftPM
```

### What did you expect to happen?

the checksums would be valid and the library would be added to the project correctly
Screenshot 2022-10-27 at 11 17 34

### OneSignal iOS SDK version

Release 3.11.4

### iOS version

15, 14, 13, 12, 11 or below

### Specific iOS version

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by shreyanshp**
# Description
## One Line Summary
**REQUIRED** - Very short description that summaries the changes in this PR.
checksums don't match

### Motivation
**REQUIRED -** Why is this code change being made? Or what is the goal of this PR? Examples: Fixes a specific bug, provides additional logging to debug future issues, feature to allow X.

### Scope
**RECOMMEND - OPTIONAL -** What is intended to be effected. What is known not to change. Example: Notifications are grouped when parameter X is set, not enabled by default.

### OPTIONAL - Other
**OPTIONAL -** Feel free to add any other sections or sub-sections that can explain your PR better.

# Testing
## Unit testing
**OPTIONAL -**  Explain unit tests added, if not clear in the code.

## Manual testing
**RECOMMEND - OPTIONAL -** Explain what scenarios were tested and the environment.
Example: Tested opening a notification while the app was foregrounded, app build with Android Studio 2020.3 with a fresh install of the OneSignal example app on a Pixel 6 with Android 12.

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [x] I have filled out all **REQUIRED** sections above
   - [x] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [x] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [x] I have included test coverage for these changes, or explained why they are not needed
   - [x] All automated tests pass, or I explained why that is not possible
   - [x] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [x] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [x] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

- - -
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1141)

### CODE REVIEW

**Comment by shreyanshp** [comment]
should fix #1140 !?

**Comment by shreyanshp** [comment]
```
fatalErrorxcodebuild: error: Could not resolve package dependencies:
  checksum of downloaded artifact of binary target 'OneSignalCore' (76ecb5ed39d25544543408a35e071bea8904883ce568ae977f8037e894a2e630) does not match checksum specified by the manifest (be0d575b6f5ad50e59e7fe49a0b808fe4cc2833358620dd7b177fe5ff7b47dea)
  checksum of downloaded artifact of binary target 'OneSignal' (fc0b8a39c68113297ec5b87617056d26d262b5c82ae47df52a9ca6e2de07d841) does not match checksum specified by the manifest (ff0c6f6c793c5d1a515f516d7f7a624e1f0ba0e5ec32bc8572e352363ead06d6)
  checksum of downloaded artifact of binary target 'OneSignalOutcomes' (a3adb9a69aad90b193062bd7911cdd0b63c6b40b3f91e71cc36f1c62927e0090) does not match checksum specified by the manifest (65b57954ce3c16019a7562d8e3e180c987e1aab04406a7c2c5825cb92a373678)
  checksum of downloaded artifact of binary target 'OneSignalExtension' (acdcaf4daf9f386340619160e1660d10b0347ea7a78ab4f5f4c5d9c5b6d974fa) does not match checksum specified by the manifest (994a897b849dacc873c22e5b0e2db9457e736c9b721ae6d0aaa1849130961e9a)
  fatalError
  
  ```

**Comment by shreyanshp** [comment]
funnily it seems you folks re-uploaded older binaries 😓 
https://github.com/OneSignal/OneSignal-iOS-SDK/commit/40bcc86eb5fc4bcf0e54d311840ecc8533f589b6

the checksum seems from previous version, nothing I can do here 😅

**Comment by fhboswell** [comment]
@shreyanshp This issue has been resolved.

**Pull request closed without merging**
