### PR TITLE
Feature app defined setLanguage

### PR DESCRIPTION
**Pull request by tanaynigam**
# Description
## Line Summary
Add feature app-defined language implementation. A user can define their own language setting to be used by OneSignal-SDK

## Details
* Add Language implementations that include `LanguageContext` that relies on strategy to determine and retrieve language from app-defined implementation or device implementation
* Add `setLanguage` method that provides an interface for a user to define app-defined language
* Add `OSUserStateSynchronizer`, `OSUserStateSMSSynchronizer` and `OSUserStateEmailSynchronizer` for network calls
* Add network call implementations in `setLanguageOnServer` called from `setLanguage` in OneSignal implementation

## Test
* Test device using button click to call OneSignal.setLanguage to set it to language different from language defined by the device. OneSignal app dashboard reflects the language set using OneSignal.setLanguage

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948)

### CODE REVIEW

**Review by emawby — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, 9 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948)* status: 16 of 17 files reviewed, 11 unresolved discussions (waiting on @Jeasmine, @jkasten2, and @tanaynigam)

___
*[iOS_SDK/OneSignalSDK/Source/OneSignal.h, line 568 at r2](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-McKnKLaB_r4aA6O2YSu:-McKnKLaB_r4aA6O2YSv:b8h20yl) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/fcf406bc121a1b3bfc5b95e83e14bb481fb5b8eb/iOS_SDK/OneSignalSDK/Source/OneSignal.h#L568)):*
> ```objc
> #pragma mark Language
> 
> + (void)setLanguage:(NSString * _Nonnull)language;
> ```

Lets add a comment indicating what format we expect the language string to be in
___
*[iOS_SDK/OneSignalSDK/Source/OneSignal.m, line 1900 at r2](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-McKnVn77j1ieGCFt8HX:-McKnVn77j1ieGCFt8HY:b-blerr5) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/fcf406bc121a1b3bfc5b95e83e14bb481fb5b8eb/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L1900)):*
> ```objc
>             }
>             
>             //TODO: Check for Pending Language State and add a put call for it
> ```

Is this todo required before release of the feature?
___
*[iOS_SDK/OneSignalSDK/Source/Language/LanguageContext.h, line 5 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-McKlkly7xHKUf2qv4K4:-McKlkly7xHKUf2qv4K5:b-y87eqp) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/09002db7c59129c6c21c95a50fe2769dbb56c442/iOS_SDK/OneSignalSDK/Source/Language/LanguageContext.h#L5)):*
> ```objc
> //  OneSignal
> //
> //  Created by Tanay Nigam on 6/3/21.
> ```

We use a standard copyright comment at the top of all new files. Copy and paste one from an existing file and use it in all the new files in this pr
___
*[iOS_SDK/OneSignalSDK/Source/Language/LanguageContext.h, line 12 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-McKmWDjBIMNPYbvTsVc:-McKmWDjBIMNPYbvTsVd:b2z31da) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/09002db7c59129c6c21c95a50fe2769dbb56c442/iOS_SDK/OneSignalSDK/Source/Language/LanguageContext.h#L12)):*
> ```objc
> #import "LanguageProvider.h"
> 
> #ifndef LanguageContext_h
> ```

The LanguageContext_h lines can be deleted. All you need is the "@interface LanguageContext line and @end"
___
*[iOS_SDK/OneSignalSDK/Source/Language/LanguageContext.h, line 13 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-McKmV6w3zHAxNtCeJb5:-McKmV6w3zHAxNtCeJb6:bc5vf4w) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/09002db7c59129c6c21c95a50fe2769dbb56c442/iOS_SDK/OneSignalSDK/Source/Language/LanguageContext.h#L13)):*
> ```
> #ifndef LanguageContext_h
> #define LanguageContext_h
> ```
___
*[iOS_SDK/OneSignalSDK/Source/Language/LanguageContext.h, line 15 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-McKlxX-Au7b4DBWo6GW:-McKlxX-Au7b4DBWo6GX:bwwyqnk) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/09002db7c59129c6c21c95a50fe2769dbb56c442/iOS_SDK/OneSignalSDK/Source/Language/LanguageContext.h#L15)):*
> ```objc
> #define LanguageContext_h
> 
> #define OSUD_LANGUAGE                                                       @"OSUD_LANGUAGE"                                                    // * OSUD_LANGUAGE
> ```

We have a file called OneSignalCommonDefines that OSUD_LANGUAGE can go in
___
*[iOS_SDK/OneSignalSDK/Source/Language/LanguageContext.h, line 17 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-McKm9HODZxFoRlxMYvK:-McKm9HODZxFoRlxMYvL:b5284p7) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/09002db7c59129c6c21c95a50fe2769dbb56c442/iOS_SDK/OneSignalSDK/Source/Language/LanguageContext.h#L17)):*
> ```objc
> #define OSUD_LANGUAGE                                                       @"OSUD_LANGUAGE"                                                    // * OSUD_LANGUAGE
> 
> NS_ASSUME_NONNULL_BEGIN
> ```

Lets prefer to explicitly write out nonnull and null instead of using these compiler directives
___
*[iOS_SDK/OneSignalSDK/Source/Language/LanguageContext.h, line 29 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-McKm4oKCpldGtEfvYz9:-McKm4oKCpldGtEfvYzA:buwrzyz) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/09002db7c59129c6c21c95a50fe2769dbb56c442/iOS_SDK/OneSignalSDK/Source/Language/LanguageContext.h#L29)):*
> ```objc
> NS_ASSUME_NONNULL_END
> 
> #endif /* LanguageContext_h */
> ```

This line can be deleted
___
*[iOS_SDK/OneSignalSDK/Source/Language/LanguageProvider.h, line 9 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-McKmiHODtF9sz6e1tCH:-McKmiHODtF9sz6e1tCI:bxkidm) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/09002db7c59129c6c21c95a50fe2769dbb56c442/iOS_SDK/OneSignalSDK/Source/Language/LanguageProvider.h#L9)):*
> ```objc
> //
> 
> #ifndef LanguageProvider_h
> ```

Same as with language context we don't need the LanguageProvider_h compiler directives only the @protocl and @end
___
*[iOS_SDK/OneSignalSDK/Source/Language/LanguageProviderAppDefined.h, line 12 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-McKmrj00XuVJCDRUc13:-McKmrj00XuVJCDRUc14:b-ctpxjk) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/09002db7c59129c6c21c95a50fe2769dbb56c442/iOS_SDK/OneSignalSDK/Source/Language/LanguageProviderAppDefined.h#L12)):*
> ```objc
> #import "LanguageProvider.h"
> 
> #ifndef LanguageProviderAppDefined_h
> ```

Same comments as the other headers
___
*[iOS_SDK/OneSignalSDK/Source/Language/LanguageProviderDevice.h, line 14 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-McKn4in8jo74ieZOSlP:-McKn4io2tnE2C3rAwrd:btqp26n) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/09002db7c59129c6c21c95a50fe2769dbb56c442/iOS_SDK/OneSignalSDK/Source/Language/LanguageProviderDevice.h#L14)):*
> ```objc
> #define DEFAULT_LANGUAGE                                                    @"en"                                                               // * OSUD_LANGUAGE
> 
> NS_ASSUME_NONNULL_BEGIN
> ```

same comments as other headers.

**Review by jkasten2 — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948)* status: all files reviewed, 11 unresolved discussions (waiting on @emawby, @Jeasmine, and @tanaynigam)

___
*[iOS_SDK/OneSignalSDK/Source/Language/LanguageContext.h, line 13 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-McKmV6w3zHAxNtCeJb5:-McM_rwF2R03lhiX9Pip:bnxl7lj) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/09002db7c59129c6c21c95a50fe2769dbb56c442/iOS_SDK/OneSignalSDK/Source/Language/LanguageContext.h#L13)):*
<details><summary><i>Previously, emawby (Elliot Mawby) wrote…</i></summary><blockquote>

> ```
> #ifndef LanguageContext_h
> #define LanguageContext_h
> ```

</blockquote></details>

It seems include guards are not needed with Objective-C:
https://en.wikipedia.org/wiki/Include_guard

I had issue with this in the past so thought we needed to continue using them but seems I was wrong.
___
*[iOS_SDK/OneSignalSDK/Source/Language/LanguageContext.h, line 15 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-McKlxX-Au7b4DBWo6GW:-McMf_VAENm0AbkmEoqH:b-z9f3se) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/09002db7c59129c6c21c95a50fe2769dbb56c442/iOS_SDK/OneSignalSDK/Source/Language/LanguageContext.h#L15)):*
<details><summary><i>Previously, emawby (Elliot Mawby) wrote…</i></summary><blockquote>

We have a file called OneSignalCommonDefines that OSUD_LANGUAGE can go in
</blockquote></details>

I think we should stop adding to `OneSignalCommonDefines`, as we shouldn't have to touch core files to add a new module / feature. Referring to the open closed principle here.

**Review by Jeasmine — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948)* status: all files reviewed, 15 unresolved discussions (waiting on @emawby and @tanaynigam)

___
*[iOS_SDK/OneSignalSDK/Source/OneSignal.m, line 2713 at r2](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-McjmAhP2GXlkQfcphxG:-McjmAhQ-vRT2ZYbOT4S:bnharsf) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/fcf406bc121a1b3bfc5b95e83e14bb481fb5b8eb/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L2713)):*
> ```objc
>     
>     //Can't send Language if there exists not LanguageContext or language
>     if (languageContext.language)
> ```

if there is language to send to the server

    let languageProviderAppDefined = [LanguageProviderAppDefined new];
    [languageProviderAppDefined setLanguage:language]; <---- Should we undo this set?
    [languageContext setStrategy:languageProviderAppDefined];
___
*[iOS_SDK/OneSignalSDK/Source/OneSignal.m, line 2721 at r2](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-Mcjm1Kw0x0Ir8tZVqge:-Mcjm1Kw0x0Ir8tZVqgf:bomeqqc) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/fcf406bc121a1b3bfc5b95e83e14bb481fb5b8eb/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L2721)):*
> ```objc
>     
>     // return if the user has not granted privacy permissions
>     if ([self shouldLogMissingPrivacyConsentErrorWithMethodName:nil])
> ```

do we need this privacy consent check? since this is already covered by setLanguage, is this method being called from somewhere else?
___
*[iOS_SDK/OneSignalSDK/Source/OSUserStateEmailSynchronizer.m, line 99 at r2](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-Mcjnspz1Y9Nejglu3Cj:-Mcjnspz1Y9Nejglu3Ck:b-du855a) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/fcf406bc121a1b3bfc5b95e83e14bb481fb5b8eb/iOS_SDK/OneSignalSDK/Source/OSUserStateEmailSynchronizer.m#L99)):*
> ```objc
> - (OSRequestUpdateLanguage *)setLanguage:(NSString *)language
>                                withAppId:(NSString *)appId {
>     return [OSRequestUpdateLanguage withUserId:[self getId] appId:appId language:language emailAuthToken:[self getEmailAuthHashToken] externalIdAuthToken:[self getExternalIdAuthHashToken]];
> ```

Do you need to override this method? This is the default behavior for UserStateSynchronized.m
___
*[iOS_SDK/OneSignalSDK/Source/Language/LanguageProviderAppDefined.m, line 19 at r2](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-McjoOtdERxFHXy5svxM:-McjoOtdERxFHXy5svxN:bnasmef) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/fcf406bc121a1b3bfc5b95e83e14bb481fb5b8eb/iOS_SDK/OneSignalSDK/Source/Language/LanguageProviderAppDefined.m#L19)):*
> ```objc
> 
> - (NSString *)language {
>     return [OneSignalUserDefaults.initStandard  getSavedStringForKey:OSUD_LANGUAGE defaultValue:DEFAULT_LANGUAGE];
> ```

I think there are 2 spaces between
"initStandard  getSavedStrin"

can you remove 1, thanks!

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r3.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948)* status: all files reviewed, 18 unresolved discussions (waiting on @adamschlesinger, @emawby, and @tanaynigam)

___
*[iOS_SDK/OneSignalSDK/Source/OneSignal.h, line 568 at r2](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-McKnKLaB_r4aA6O2YSu:-MdZgLgk8yfTmjGLU8DW:bi0d86p) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/fcf406bc121a1b3bfc5b95e83e14bb481fb5b8eb/iOS_SDK/OneSignalSDK/Source/OneSignal.h#L568)):*
<details><summary><i>Previously, emawby (Elliot Mawby) wrote…</i></summary><blockquote>

Lets add a comment indicating what format we expect the language string to be in
</blockquote></details>

Good idea, that way the the developer won't have to check the docs for this detail.
___
*[iOS_SDK/OneSignalSDK/Source/OneSignal.m, line 2718 at r3](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-MdZejZP3IQGpNBa7LaA:-MdZejZP3IQGpNBa7LaB:bc5eosc) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/7bc28c17612a4ad9b23f2e0c20184b2ff86d7632/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L2718)):*
> ```objc
>         return;
>     
>     //Can't send Language if there exists not LanguageContext or language
> ```

We only need to have a `languageContext` instance. It doesn't matter what the current `.language` value is.
___
*[iOS_SDK/OneSignalSDK/Source/OneSignal.m, line 2726 at r3](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-MdZfRp7AXUa9nXA4l-e:-MdZfRp85dXERhW99SDm:b-txray) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/7bc28c17612a4ad9b23f2e0c20184b2ff86d7632/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L2726)):*
> ```objc
>     
>     [OneSignal.stateSynchronizer updateLanguage:language appId:appId withSuccess:^(NSDictionary *results) {
>         let languageProviderAppDefined = [LanguageProviderAppDefined new];
> ```

We should update the languageContext with the new strategy before making a network call. This way the language is still set if the device has networking issues, or if an on_session call happens to be done at the same time as this PUT call.
___
*[iOS_SDK/OneSignalSDK/UnitTests/LanguageTest.m, line 6 at r3](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-MdZTwkB55HO4qm93Trs:-MdZTwkB55HO4qm93Trt:b-pq4cww) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/7bc28c17612a4ad9b23f2e0c20184b2ff86d7632/iOS_SDK/OneSignalSDK/UnitTests/LanguageTest.m#L6)):*
> ```objc
> //
> //  Created by Tanay Nigam on 6/24/21.
> //  Copyright © 2021 Hiptic. All rights reserved.
> ```

Update comment header

**Review by emawby — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948)* status: all files reviewed, 19 unresolved discussions (waiting on @adamschlesinger, @emawby, and @tanaynigam)

___
*[iOS_SDK/OneSignalSDK/Source/OSStateSynchronizer.m, line 405 at r3](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-Mdx3V6u8306Zd4EJSx-:-Mdx3V6u8306Zd4EJSx0:b8mhpp0) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/7bc28c17612a4ad9b23f2e0c20184b2ff86d7632/iOS_SDK/OneSignalSDK/Source/OSStateSynchronizer.m#L405)):*
> ```objc
>         }
>         
>         if (successBlock)
> ```

When will we call the failure block here? I think we need to check the results dictionary and call the failure block when appropriate. As it is we are always calling success

**Review by Jeasmine — COMMENTED** [review]
> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948)* status: all files reviewed, 23 unresolved discussions (waiting on @adamschlesinger, @emawby, and @tanaynigam)

___
*[iOS_SDK/OneSignalSDK/Source/OSStateSynchronizer.m, line 405 at r3](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-Mdx3V6u8306Zd4EJSx-:-Me76gKw0I2ElQIXvXwD:b-vymxvn) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/7bc28c17612a4ad9b23f2e0c20184b2ff86d7632/iOS_SDK/OneSignalSDK/Source/OSStateSynchronizer.m#L405)):*
<details><summary><i>Previously, emawby (Elliot Mawby) wrote…</i></summary><blockquote>

When will we call the failure block here? I think we need to check the results dictionary and call the failure block when appropriate. As it is we are always calling success
</blockquote></details>

Maybe inside the else block, the failure block can be called?
___
*[iOS_SDK/OneSignalSDK/Source/OSStateSynchronizer.m, line 398 at r4](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-Me76mOC1geQEeo6itH6:-Me76mOC1geQEeo6itH7:byp5hww) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/b3e19840f23831bb54482d1ae8f3ef6e590b6dd9/iOS_SDK/OneSignalSDK/Source/OSStateSynchronizer.m#L398)):*
> ```objc
>             [OneSignalUserDefaults.initStandard saveStringForKey:OSUD_LANGUAGE withValue:language];
>         }
>         else if (results[OS_EMAIL] && results[OS_EMAIL][OS_SUCCESS] && [results[OS_EMAIL][OS_SUCCESS] boolValue]) {
> ```

I think that as code style, we are putting the else at the same level of the previous "}"
Like "} else if"
___
*[iOS_SDK/OneSignalSDK/UnitTests/LanguageTest.m, line 62 at r4](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-Me773oh-N1_vw2jPvgi:-Me773oh-N1_vw2jPvgj:br5oa1y) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/b3e19840f23831bb54482d1ae8f3ef6e590b6dd9/iOS_SDK/OneSignalSDK/UnitTests/LanguageTest.m#L62)):*
> ```
> [UnitTestCommonMethods initOneSignal_andThreadWait];
> ```
isn't "[UnitTestCommonMethods initOneSignal_andThreadWait];" already running runBackgroundThreads?
___
*[iOS_SDK/OneSignalSDK/UnitTests/LanguageTest.m, line 70 at r4](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-Me77C8-7wHPmb8YDrNk:-Me77C8-7wHPmb8YDrNl:b-4h9nk9) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/b3e19840f23831bb54482d1ae8f3ef6e590b6dd9/iOS_SDK/OneSignalSDK/UnitTests/LanguageTest.m#L70)):*
> ```objc
> 
> -(void)testSetLanguage_afterOnSession {
>     // 2. Open app
> ```

update comment numbers
___
*[iOS_SDK/OneSignalSDK/UnitTests/LanguageTest.m, line 91 at r4](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-Me77QNHBMm5lIQVgqRL:-Me77QNHBMm5lIQVgqRM:b8hh2om) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/b3e19840f23831bb54482d1ae8f3ef6e590b6dd9/iOS_SDK/OneSignalSDK/UnitTests/LanguageTest.m#L91)):*
> ```objc
>     XCTAssertEqualObjects(OneSignalClientOverrider.lastHTTPRequest[@"language"], @"fr");
> }
> ```

We might need to test the failing cases, what do you think?

**Review by jkasten2 — APPROVED** [review]
@tanaynigam PR looks good after addressing @jeasmine latest comments.

> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/948#-:-Me7W9fBCXni-sPTP9QG:bjopwr4)* status: all files reviewed, 21 unresolved discussions (waiting on @adamschlesinger, @emawby, and @tanaynigam)

**Review by emawby — APPROVED** [review]
Approved after resolving Jeas comments!

**Review by Jeasmine — APPROVED** [review]
LGTM

**Pull request merged**
