### PR TITLE
Make web views inspectable

### LINKED ISSUE #1277: [Bug]: Web Push templates are not inspectable in Test Flight
### What happened?

The SDK does not allow Safari inspection of OneSignal web views.

CleanShot CleanShot 2023-07-18 at 15 52 56

### Steps to reproduce?

```Markdown
1. Install OneSignal SDK, create a TestFlight build of the application.
2. Send a web push to yourself in the app.
3. Attempt to inspect via [Safari remote inspector](https://help.remo.co/en/support/solutions/articles/63000251570-how-to-activate-the-iphone-debug-console-or-web-inspector-).
```

### What did you expect to happen?

I should be able to inspect web views for debugging.

### OneSignal iOS SDK version

3.12.5

### iOS version

15

### Specific iOS version

```Markdown
iOS 16.4 and up
```

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by casey-chow**
# Description
## One Line Summary

Adds Safari inspectability for all WKWebView instances, closes #1277. See https://webkit.org/blog/13936/enabling-the-inspection-of-web-content-in-apps/ for details.

### Motivation
This PR allows developers to view WKWebView instances inside Safari's inspection mechanism for iOS devices. This is necessary for us to verify click tracking in OneSignal Web Views.

# Testing

No automated testing added since this is functionally a configuration change.

## Manual testing

I've not been able to succeed testing this, seems like the framework cannot be built without certificates.

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [x] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [ ] I have filled out all **REQUIRED** sections above
   - [x] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [ ] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [x] I have included test coverage for these changes, or explained why they are not needed
   - [x] All automated tests pass, or I explained why that is not possible
   - [x] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [x] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [x] I have reviewed this PR myself, ensuring it meets each checklist item

- - -
This change is [Reviewable](https://reviewable.io/reviews/OneSignal/OneSignal-iOS-SDK/1286)

### CODE REVIEW

**Review by emawby — CHANGES_REQUESTED** [review]
Hello thank you for your contribution! It looks like this is failing to build. I believe the Objective-C version of this property is named `inspectable` (the getter is `isInspectable`)

**Comment by casey-chow** [comment]
> Hello thank you for your contribution! It looks like this is failing to build. I believe the Objective-C version of this property is named `inspectable` (the getter is `isInspectable`)

Awesome, thanks! I pushed a fix, do you have guidance about getting this to build in an existing project? I wasn't able to due to certificate signing issues.

**Review by emawby — CHANGES_REQUESTED** [review]
Good question you likely need to change the bundle id and development team in the dev app. One last fix 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/OneSignal/OneSignal-iOS-SDK/1286#-:-Nah3VOGCstUb5CQlO53:bdnfpys)* status: all files reviewed, 2 unresolved discussions (waiting on @casey-chow, @jkasten2, and @rgomezp)

___
*[`iOS_SDK/OneSignalSDK/Source/OneSignalWebView.m` line 45 at r1](https://reviewable.io/reviews/OneSignal/OneSignal-iOS-SDK/1286#-Nah3cPz9bvCgCUq8or6:-Nah3cPz9bvCgCUq8or7:b-w3mt1k) ([raw file](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/8581ca199df4930f7d4bfd7bcc136712bac1eae5/iOS_SDK/OneSignalSDK/Source/OneSignalWebView.m#L45)):*
> ```objc
>     _webView.navigationDelegate = self;
>     // https://webkit.org/blog/13936/enabling-the-inspection-of-web-content-in-apps/
>     if (@available(macOS 13.3, iOS 16.4, *)) {
> ```

Let's add a condition to this to only enable inspectability if the app is being run in debug mode.
___
*[`iOS_SDK/OneSignalSDK/Source/OSInAppMessageView.m` line 114 at r1](https://reviewable.io/reviews/OneSignal/OneSignal-iOS-SDK/1286#-Nah3xYl8NT_MT015cyN:-Nah3xYl8NT_MT015cyO:b-w3mt1k) ([raw file](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/8581ca199df4930f7d4bfd7bcc136712bac1eae5/iOS_SDK/OneSignalSDK/Source/OSInAppMessageView.m#L114)):*
> ```objc
>     self.webView.opaque = NO;
>     // https://webkit.org/blog/13936/enabling-the-inspection-of-web-content-in-apps/
>     if (@available(macOS 13.3, iOS 16.4, *)) {
> ```

Let's add a condition to this to only enable inspectability if the app is being run in debug mode.

**Comment by casey-chow** [comment]
> Let's add a condition to this to only enable inspectability if the app is being run in debug mode.

The main issue I'm facing is our web developers are facing issues in the production version of the app, so we'd like to have access in TestFlight. This is especially important because we need to test against production data/non-sandbox environment, which we can't on a debug build. The other option would be to expose this configuration in the API, but I opted to avoid making any API changes.

**Review by emawby — COMMENTED** [review]
That makes sense in order to allow debugging in TestFlight lets have the condition be OneSignal's log level as debug or higher. I do not want to have inspectability on by default. This behavior would also match the Android SDK's Webview inspectability behavior.

> *[Reviewable](https://reviewable.io/reviews/OneSignal/OneSignal-iOS-SDK/1286#-:-NamTTnPEa5Qu1t0iZ5w:b-o792ri)* status: all files reviewed, 2 unresolved discussions (waiting on @casey-chow, @jkasten2, and @rgomezp)

**Comment by casey-chow** [comment]
@emawby made the requisite changes, please take a look!

**Review by emawby — APPROVED** [review]

**Review by jkasten2 — APPROVED** [review]

**Pull request merged**
