### PR TITLE
Old Modular Distribution

### PR DESCRIPTION
**Pull request by emawby**
# Description
## One Line Summary
This branch updates the Cocoapods and Swift PM distribution of our iOS SDK for the modularized branch.

### Build script for XCFrameworks
`build_all_frameworks.sh`
This script builds each module as an XCFramework in the same manner as the OneSignalFramework target was built.

### Cocoapods
OneSignalXCFramework pod now includes subspecs for OneSignalCore, OneSignalOutcomes and OneSignalExtension. These subspecs can be used to get rid of the extension warning and in the future will allow customers to remove location.

### SwiftPM
Package.swift is updated to use binary targets like the OneSignal-XCFramework repository. This means that the build tools minimum was increased from 5.1 (Xcode 11) to 5.3 (Xcode 12)

Products:
- OneSignal
- OneSignalExtension

Swift PM binary targets cannot have dependencies. To get around this limitation we need to create dummy wrapper targets that contain no code themselves, but depend on the appropriate binary targets. This allows us to distribute the binary XCFrameworks that depend on each other.

#### Updating the Package.swift file
The `update_swift_package.sh` script from the OneSignal-XCFramework repo is now in this repo as well. This script zips each of the modules XCFrameworks, sets the hash, and updates the release number in the url to the zipped framework.
iOS releases will now need to have each modules zipped framework attached.

### Carthage
Carthage works by building all framework schemes as XCFrameworks when using the carthage build/update --use-xcframeworks command. Then the user will need to drag each XCFramework into their app target. The setup instructions will need to be updated to reflect this.

### Motivation
This PR allows us to distribute the modularized version of the iOS SDK via Cocoapods, SwiftPM, and Carthage.

# Testing
## Manual testing
I have successfully tested via SwiftPM, Carthage, and Cocoapods on a test app.

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes
   - [x] Distribution

# Checklist
## Overview
   - [X] I have filled out all **REQUIRED** sections above
   - [X] PR does one thing
   - [X] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [X] I have included test coverage for these changes, or explained why they are not needed
   - [x] All automated tests pass, or I explained why that is not possible
   - [X] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [ ] Code is as readable as possible.
   - [ ] I have reviewed this PR myself, ensuring it meets each checklist item

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1026)

### CODE REVIEW

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> Reviewed 166 of 273 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1026)* status: 166 of 273 files reviewed, 4 unresolved discussions (waiting on @emawby, @Jeasmine, and @nan-li)

___
*[OneSignalCore.podspec, line 10 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1026#-Mpn4RA23V-iG-D4xcUC:-Mpn4RA30gH07i414wlq:bmvqrg3) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/a80dea19beaa9fac4c5cee4a5591e4c434d87589/OneSignalCore.podspec#L10)):*
> ```Ruby
>     
>     s.source           = { :git => "https://github.com/OneSignal/OneSignal-iOS-SDK.git", :tag => s.version.to_s }
>     s.platform     = :ios
> ```

nit, in consistent spacing before equals in this file.
___
*[OneSignalExtension.podspec, line 12 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1026#-Mpn4aPu124KDk3PSaMQ:-Mpn4aPu124KDk3PSaMR:b-fvyiy) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/a80dea19beaa9fac4c5cee4a5591e4c434d87589/OneSignalExtension.podspec#L12)):*
> ```Ruby
>     s.platform     = :ios
>     s.requires_arc = true
>     s.dependency 'OneSignalCore'
> ```

It would be more clear if these two `dependency` lines where in their own consistent section of our `.podspec` files. May just at the end with a extra blank line above them so it is clear they have dependencies.
___
*[Package.swift, line 12 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1026#-Mpn5OrhDzuwKGKnEaBO:-Mpn5OrhDzuwKGKnEaBP:b-uknuzd) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/a80dea19beaa9fac4c5cee4a5591e4c434d87589/Package.swift#L12)):*
> ```Swift
>             name: "OneSignal",
>             targets: ["OneSignalWrapper"]),
>         .library(
> ```

Won't be want a OneSignalApp target too?, it would just the `OneSignalExtension`.
___
*[iOS_SDK/OneSignalSDK/build_all_frameworks.sh, line 27 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1026#-Mpn5qXFBWaHAHhKNsKA:-Mpn5qXFBWaHAHhKNsKB:b-mngr6r) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/a80dea19beaa9fac4c5cee4a5591e4c434d87589/iOS_SDK/OneSignalSDK/build_all_frameworks.sh#L27)):*
> ```Shell
> echo "Archiving ${FRAMEWORK_NAME}"
> 
> xcodebuild archive ONLY_ACTIVE_ARCH=NO -scheme ${BUILD_SCHEME} -destination="generic/platform=iOS Simulator" -archivePath "${SIMULATOR_ARCHIVE_PATH}" -sdk iphonesimulator SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES
> ```

Seems like a lot of the code in this file is repeated, could add function for re-use to improve maintainability.

**Review by emawby — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1026)* status: 96 of 293 files reviewed, 3 unresolved discussions (waiting on @emawby, @Jeasmine, @jkasten2, and @nan-li)

___
*[OneSignalExtension.podspec, line 12 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1026#-Mpn4aPu124KDk3PSaMQ:-MqVgY5U3JVZsn_EUyh9:b-896fix) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/a80dea19beaa9fac4c5cee4a5591e4c434d87589/OneSignalExtension.podspec#L12)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

It would be more clear if these two `dependency` lines where in their own consistent section of our `.podspec` files. May just at the end with a extra blank line above them so it is clear they have dependencies.
</blockquote></details>

Done.
___
*[iOS_SDK/OneSignalSDK/build_all_frameworks.sh, line 27 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1026#-Mpn5qXFBWaHAHhKNsKA:-MqVgRnjCjrBtBBYt2X9:b-896fix) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/a80dea19beaa9fac4c5cee4a5591e4c434d87589/iOS_SDK/OneSignalSDK/build_all_frameworks.sh#L27)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Seems like a lot of the code in this file is repeated, could add function for re-use to improve maintainability.
</blockquote></details>

Done.

**Review by jkasten2 — COMMENTED** [review]
> Reviewed 39 of 273 files at r1, 158 of 158 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1026)* status: all files reviewed, 1 unresolved discussion (waiting on @emawby, @Jeasmine, and @nan-li)

**Comment by jkasten2** [comment]
If I try to use the  `OneSignalXCFramework` pod in a new Xcode project I get a crash on startup.
```
dyld: Library not loaded: @rpath/OneSignalCore.framework/OneSignalCore
  Referenced from: /private/var/containers/Bundle/Application/AB5DE9D2-B306-4087-9FFA-452FC9B687A8/OneSignalModularTestObjc.app/Frameworks/OneSignal.framework/OneSignal
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
```
Steps to reproduce.
1. Run `build_all_frameworks.sh`
2. Create a new Objective-C project in Xcode.
3. Run `pod init`
4. Add local pod `pod 'OneSignalXCFramework', :path => '~/Documents/repos/OneSignal-iOS-SDK/'`
5. Run `pod install`
6. Run `xed .` to reopen your Xcode project.
7. Run on either a sim or real device and observe the crash.

**Review by emawby — COMMENTED** [review]
Does this work if you add all of the local dependent local pods as well instead of just OneSignalXCFramework? Cocoapods should be handling those dependencies for us but maybe the podspecs need to be more specific since it isn't released yet

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1026#-:-MvtEKEnC3gJ5Cx4Gr8q:bvmynn5)* status: all files reviewed, 1 unresolved discussion (waiting on @emawby, @Jeasmine, and @nan-li)

**Pull request closed without merging**
