### PR TITLE
Interruption Level and Relevance Score

### PR DESCRIPTION
**Pull request by emawby**
This PR adds the `interruptionLevel` string and the `relevanceScore` double to the `OSNotification` object. These are iOS 15 only properties that can be sent via APNs payload local notification creation. OneSignal does not change any behavior according to these properties, but they will now appear in the `OSNotification` object for OneSignal notifications that utilize them.

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/963)

### CODE REVIEW

**Review by jkasten2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/963#-:-MfEG-k52fHsIFn9GWhu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nan-li)

**Review by nan-li — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/963#-:-MfiQ50m9AB2s7CxbzOX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @emawby)

**Review by nan-li — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/963)* status: all files reviewed, 1 unresolved discussion (waiting on @emawby)

___
*[iOS_SDK/OneSignalSDK/Source/OneSignal.h, line 134 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/963#-MfiTeDs9x2WqpfvbrsY:-MfiTbc86drw5monVsCT:bphmdjb) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/1663cba5536b3d98c7343bac655fae8bb9dfbd25/iOS_SDK/OneSignalSDK/Source/OneSignal.h#L134)):*
> ```
> readonly, nullable
> ```
Just wondering: why does this item have `nullable` while `interruptionLevel` does not?

**Review by Jeasmine — APPROVED** [review]
We will need to add this data to objects in the Wrappers, correct? If so, do you agree with having a ticket for this not to lose track of it?

**Pull request merged**
