### PR TITLE
IAM liquid templating support

### PR DESCRIPTION
**Pull request by emawby**
This PR adds support for IAM liquid templating tag substitution
The liquid rendering is handled by a javascript library added to the IAM by the dashboard. The SDKs just need to inject the tags for the player into the IAM html.

- Injects tags into the IAM via the iamInfo.tags object in the IAM. I had to add it into the HTML before it was loaded into the webview to get it to render properly. This takes place in `OSInAppMessageView`
- This PR also adds `OSPlayerTags` to cache tags in `NSUserDefaults` on the device
- Tags are retrieved in parallel with the IAM HTML if a new property `has_liquid` is true in the IAM json. Tags will only be retrieved once per session. 
- currently is targeting local host for testing. This will be removed before merging

This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/887)

### CODE REVIEW

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 7 of 7 files at r2, 1 of 3 files at r3, 1 of 2 files at r4, 1 of 6 files at r5, 1 of 3 files at r6, 1 of 3 files at r7, 3 of 4 files at r8, 3 of 6 files at r9, 6 of 6 files at r10.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/887)* status: all files reviewed, 7 unresolved discussions (waiting on @emawby)

___
*[iOS_SDK/OneSignalDevApp/OneSignalDevApp/AppDelegate.m, line 99 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/887#-MV-5BlWBe96ij1XJKYb:-MV-5BlWBe96ij1XJKYc:bihq536) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/932477607d1afdb2a9380ed9f7cf0070b84b9d3b/iOS_SDK/OneSignalDevApp/OneSignalDevApp/AppDelegate.m#L99)):*
> ```objc
> }
> 
> #define ONESIGNAL_APP_ID_KEY_FOR_TESTING @"1bcc4195-2039-4b18-83d7-2ab5b98daf76"
> ```

This is only a dev project but I recommend we don't change the app_id in a feature PR
___
*[iOS_SDK/OneSignalDevApp/OneSignalDevApp/AppDelegate.m, line 82 at r10](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/887#-MV-72_5ACP5upxdQ41e:-MV-72_5ACP5upxdQ41f:b-xkfyvc) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/50341a8d5d978e16d4d092735ed0fb960d123ef4/iOS_SDK/OneSignalDevApp/OneSignalDevApp/AppDelegate.m#L82)):*
> ```objc
>     [OneSignal setLaunchURLsInApp:YES];
>     [OneSignal setProvidesNotificationSettingsView:NO];
>     //[OneSignal sendTag:@"player_name" value:@"cached tag works!"];
> ```

Remove commented out code
___
*[iOS_SDK/OneSignalSDK/Source/OneSignal.m, line 422 at r2](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/887#-MV-5uaPDwILaJ4IZqZ0:-MV-5uaPDwILaJ4IZqZ1:b-79a20o) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/d79ba1ad83a6c68aeb2a211f573236ff849e6119/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L422)):*
> ```objc
> 
> + (NSDictionary *)getPlayerTags {
>     NSLog(@"ECM player tags: %@", playerTags);
> ```

Remove NSLog
___
*[iOS_SDK/OneSignalSDK/Source/OneSignalCommonDefines.h, line 36 at r10](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/887#-MV-7ELo56TkoizH4eXQ:-MV-7ELo56TkoizH4eXR:b-c490mv) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/50341a8d5d978e16d4d092735ed0fb960d123ef4/iOS_SDK/OneSignalSDK/Source/OneSignalCommonDefines.h#L36)):*
> ```objc
> #define OS_API_VERSION @"1"
> #define OS_API_ACCEPT_HEADER @"application/vnd.onesignal.v" OS_API_VERSION @"+json"
> #define OS_API_SERVER_URL @"http://192.168.1.86:3000/api/v1/"
> ```

URL needs to be put back
___
*[iOS_SDK/OneSignalSDK/Source/OSInAppMessage.m, line 179 at r10](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/887#-MV-7T_D8GgL66IAf7wH:-MV-7T_D8GgL66IAf7wI:b6rbhp8) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/50341a8d5d978e16d4d092735ed0fb960d123ef4/iOS_SDK/OneSignalSDK/Source/OSInAppMessage.m#L179)):*
> ```objc
>     
>     if (self.hasLiquid) {
>         json[@"has_liquid"] = @"1";
> ```

I would expect this to be a boolean in JSON.
___
*[iOS_SDK/OneSignalSDK/Source/OSMessagingController.m, line 294 at r10](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/887#-MV-8cO6-4SaW9v08eii:-MV-8cO6-4SaW9v08eij:b-c0ot9q) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/50341a8d5d978e16d4d092735ed0fb960d123ef4/iOS_SDK/OneSignalSDK/Source/OSMessagingController.m#L294)):*
> ```objc
> 
> - (void)loadTags {
>     self.loadedTags = YES;
> ```

Shouldn't loadedTags be set to `true` in the getTags callback below instead of here?
___
*[iOS_SDK/OneSignalSDK/UnitTests/InAppMessagingTests.m, line 217 at r10](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/887#-MV-9kViCWx8I9TZFieR:-MV-9kViCWx8I9TZFieS:b-pmxpu1) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/50341a8d5d978e16d4d092735ed0fb960d123ef4/iOS_SDK/OneSignalSDK/UnitTests/InAppMessagingTests.m#L217)):*
> ```objc
> }
> 
> - (void)testCorrectlyParsedHasLiquid {
> ```

Not sure I understand this test. Why do we want `hasLiquid` to be true on the message but not the redisplay?

**Review by emawby — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/887)* status: 9 of 16 files reviewed, 7 unresolved discussions (waiting on @emawby and @jkasten2)

___
*[iOS_SDK/OneSignalDevApp/OneSignalDevApp/AppDelegate.m, line 99 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/887#-MV-5BlWBe96ij1XJKYb:-MV2XfGz8rvepY50c8in:b4wrmbv) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/932477607d1afdb2a9380ed9f7cf0070b84b9d3b/iOS_SDK/OneSignalDevApp/OneSignalDevApp/AppDelegate.m#L99)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

This is only a dev project but I recommend we don't change the app_id in a feature PR
</blockquote></details>

I will be better about this in the future. I want to leave the commit in the history to make it easier to test and but I will revert it before asking for review next time
___
*[iOS_SDK/OneSignalDevApp/OneSignalDevApp/AppDelegate.m, line 82 at r10](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/887#-MV-72_5ACP5upxdQ41e:-MV2XeRH3fIirMQbrUBr:b-896fix) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/50341a8d5d978e16d4d092735ed0fb960d123ef4/iOS_SDK/OneSignalDevApp/OneSignalDevApp/AppDelegate.m#L82)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Remove commented out code
</blockquote></details>

Done.
___
*[iOS_SDK/OneSignalSDK/Source/OneSignal.m, line 422 at r2](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/887#-MV-5uaPDwILaJ4IZqZ0:-MV2Y6XV7RrZsg5VCT1T:b-896fix) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/d79ba1ad83a6c68aeb2a211f573236ff849e6119/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L422)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Remove NSLog
</blockquote></details>

Done.
___
*[iOS_SDK/OneSignalSDK/Source/OneSignalCommonDefines.h, line 36 at r10](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/887#-MV-7ELo56TkoizH4eXQ:-MV2Y8bqAOa6a3W54qM4:b-4aorvg) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/50341a8d5d978e16d4d092735ed0fb960d123ef4/iOS_SDK/OneSignalSDK/Source/OneSignalCommonDefines.h#L36)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

URL needs to be put back
</blockquote></details>

leaving commit in history but reverting until merge
___
*[iOS_SDK/OneSignalSDK/Source/OSInAppMessage.m, line 179 at r10](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/887#-MV-7T_D8GgL66IAf7wH:-MV2eMsiD0rhQvdt9eRx:b-896fix) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/50341a8d5d978e16d4d092735ed0fb960d123ef4/iOS_SDK/OneSignalSDK/Source/OSInAppMessage.m#L179)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

I would expect this to be a boolean in JSON.
</blockquote></details>

Done.
___
*[iOS_SDK/OneSignalSDK/UnitTests/InAppMessagingTests.m, line 217 at r10](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/887#-MV-9kViCWx8I9TZFieR:-MV2eO7rDQxSanjQtcoi:bo3k6v3) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/50341a8d5d978e16d4d092735ed0fb960d123ef4/iOS_SDK/OneSignalSDK/UnitTests/InAppMessagingTests.m#L217)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Not sure I understand this test. Why do we want `hasLiquid` to be true on the message but not the redisplay?
</blockquote></details>

I made this test more clear by adding methods to InAppMessagingHelpers

**Comment by jkasten2** [comment]
___
*[iOS_SDK/OneSignalSDK/Source/OSMessagingController.m, line 294 at r10](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/887#-MV-8cO6-4SaW9v08eii:-MVQXbma0kNQ9xF7gSFJ:b-m7kj9u) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/50341a8d5d978e16d4d092735ed0fb960d123ef4/iOS_SDK/OneSignalSDK/Source/OSMessagingController.m#L294)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Shouldn't loadedTags be set to `true` in the getTags callback below instead of here?
</blockquote></details>

The new name `calledLoadTags` makes sense now

**Review by jkasten2 — COMMENTED** [review]
PR looks good, other than the two commits that need need to be undone before we merge

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/887#-:-MVQY68bELRH__-HZdrm:b-l2icy5)* status: all files reviewed, 3 unresolved discussions (waiting on @jkasten2)

**Review by jkasten2 — APPROVED** [review]
> Reviewed 1 of 1 files at r16, 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/887)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @emawby)

**Pull request merged**
