### PR TITLE
Don't swizzle UIApplication and UNUserNotificaion delegate for tests

### PR DESCRIPTION
**Pull request by fruitcoder**
As described in #229 tests will not run if there is not host application. This PR just returns early from `load` before all the swizzling and access to the `currentNotificationCenter`.

## 
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/485)

### CODE REVIEW

**Comment by jkasten2** [comment]
@fruitcoder Thanks for the PR! Looks like this is preventing OneSignal's SDK tests from unfortunately.

I think adding a flag of some sort to the new `[processInfo processName] isEqualToString:@"xctest"]`  check you added might be required in this case to fix.

**Comment by Nightsd01** [comment]
@fruitcoder I would be curious to see what exact stacktrace/error you get when you attempt to run your tests?

As Josh says this PR will not work since it breaks _our_ tests.

**Comment by fruitcoder** [comment]
@Nightsd01 yeah I saw that on Travis, sorry. It was a bit shortsighted but fixed our issue. We see the exact same output as @benaneesh described in #229. So:
```
*** Assertion failure in -[UNUserNotificationCenter initWithBundleIdentifier:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UserNotifications_Sim/UserNotifications-101.3.13/UNUserNotificationCenter.m:64
2017-04-21 15:29:03.264 xctest[65974:4144075] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: bundleIdentifier != nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000104039d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000103a9b21e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010403de42 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010363066d -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   UserNotifications                   0x00000001089c19a6 -[UNUserNotificationCenter initWithBundleIdentifier:] + 210
	5   UserNotifications                   0x00000001089c1650 __53+[UNUserNotificationCenter currentNotificationCenter]_block_invoke + 106
	6   libdispatch.dylib                   0x0000000106d6312e _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x0000000106d4de0e dispatch_once_f + 68
	8   UserNotifications                   0x00000001089c15e3 +[UNUserNotificationCenter currentNotificationCenter] + 45
	9   MyAppTests                          0x0000000110c488f3 +[OneSignalHelper registerAsUNNotificationCenterDelegate] + 51
	10  MyAppTests                          0x0000000110c400ea +[UIApplication(OneSignal) load] + 698
	11  libobjc.A.dylib                     0x0000000103a9d0f9 call_load_methods + 246
	12  libobjc.A.dylib                     0x0000000103a9dda3 load_images + 70
	13  ???                                 0x00000001033e5c5e 0x0 + 4349385822
	14  ???                                 0x00000001033f10aa 0x0 + 4349431978
	15  ???                                 0x00000001033f023a 0x0 + 4349428282
	16  ???                                 0x00000001033f02cf 0x0 + 4349428431
	17  ???                                 0x00000001033e89eb 0x0 + 4349397483
	18  ???                                 0x00000001033ecc20 0x0 + 4349414432
	19  libdyld.dylib                       0x0000000106da9ea4 dlopen + 59
	20  CoreFoundation                      0x0000000103fec419 _CFBundleDlfcnLoadBundle + 153
	21  CoreFoundation                      0x0000000103fec29d _CFBundleLoadExecutableAndReturnError + 333
	22  Foundation                          0x000000010358052e -[NSBundle loadAndReturnError:] + 521
	23  XCTest                              0x00000001034a9cc4 _XCTestMain + 465
	24  xctest                              0x00000001033dc922 xctest + 6434
	25  libdyld.dylib                       0x0000000106dac68d start + 1
	26  ???                                 0x0000000000000005 0x0 + 5
)
```

When accessing the `currentNotificationCenter` for the first time it seems to be initialized with a `nil` bundleIdentifier

**Comment by pnemonic78** [comment]
fixes our unit tests too.

**Comment by jkasten2** [comment]
## Update
### Work around
`DISABLE_ONESIGNAL_SWIZZLING` can be set with  “arguments passed on launch” to disable OneSignal swizzling to fix this issue. This was added with PR #297.

### Auto detection
If OneSignal's own tests depend on swizzling so looking at this again I don't think `[processInfo processName] isEqualToString:@"xctest"]` is enough looking at this again.

### Still an issue?
However a lot has changed with this SDK since this issue was open. Is this still any issue with the latest OneSignal-iOS-SDK 3.4.3 for those following?

**Pull request closed without merging**
